Assignment 1: FileNameReader.h File Reference
FileNameReader.h File Reference
#include <fstream>
Functions
int readDataSource (ifstream &inputFile)
Contains all functions need to read the input file name.
int readFileName (ifstream &dataSource, ifstream &inputFile)
Function Documentation
readDataSource()
int readDataSource (ifstream & inputFile)
Contains all functions need to read the input file name.
Author
Trong Tu Le
Version
01
Definition at line 14 of file FileNameReader.cpp.
{
     int error = 0;
     ifstream dataSource("data_source.txt");
     if(!dataSource.is_open()){
         cout << "Error opening file!" << endl;
         return 1;
     }
     error = readFileName(dataSource, inputFile);
     dataSource.close();
     return error;
 }
References readFileName().
Referenced by main().
readFileName()
int readFileName (ifstream & dataSource, ifstream & inputFile)
Definition at line 33 of file FileNameReader.cpp.
{
     string fileName;
     if (getline(dataSource, fileName)) {
         // close the inputFile if its already opened
         if(inputFile.is_open()){
             inputFile.close();
         }
         // create a input stream with the target file name
         inputFile.open(fileName);
         if (!inputFile.is_open()) {
             cout << "Error opening data file: " << fileName << endl;
             return 1;
         }
     } else {
         cout << "Failed to read filename from data source." << endl;
         return 1;
     }
     return 0;
 }
Referenced by readDataSource().