Lab06: WeatherRecord Class Reference
WeatherRecord Class Reference
Encapsulates weather data including date, time, wind speed, solar radiation, and ambient air temperature.
#include <WeatherRecord.h>
Public Member Functions
WeatherRecord ()
Default constructor. Initializes all data members to their default values.
WeatherRecord (Date d, Time t, float s, float sR, float aT)
Parameterized constructor.Initializes all data members to the given values.
Date getDate () const
Get the date object.
void setDate (Date d)
Set the Date object.
Time getTime () const
Get the Time object.
void setTime (Time t)
Set the Time object.
float getSpeed () const
Get the wind speed.
void setSpeed (float s)
Set the wind speed.
float getSolarRad () const
Get the solar radiation.
void setSolarRad (float sR)
Set the solar radiation.
float getAirTemp () const
Get the air temperature.
void setAirTemp (float aT)
Set the air temperature.
Private Attributes
Date _date
Time _time
The recorded date.
float _speed
The recorded time.
float _solarRad
The wind speed.
float _airTemp
The solar radiation.
Detailed Description
Encapsulates weather data including date, time, wind speed, solar radiation, and ambient air temperature.
Author
Trong Tu Le
Version
1 Each WeatherRecord object holds a date and time of recording, along with wind speed, solar radiation, and ambient air temperature. The class provides both getters and setters for all data fields to ensure encapsulated and safe access to the data.
Definition at line 23 of file WeatherRecord.h.
Constructor & Destructor Documentation
WeatherRecord() [1/2]
WeatherRecord::WeatherRecord ()
Default constructor. Initializes all data members to their default values.
Definition at line 17 of file WeatherRecord.cpp.
                              : _date(Date()), _time(Time()), _speed(0), _solarRad(0), _airTemp(0){
 }
WeatherRecord() [2/2]
WeatherRecord::WeatherRecord (Date d, Time t, float s, float sR, float aT)
Parameterized constructor.Initializes all data members to the given values.
Parameters
d Date
t Time
s wind speed
sR solar radiation
aT air temperature
Definition at line 23 of file WeatherRecord.cpp.
                                                                         : _date(d), _time(t), _speed(s), _solarRad(sR), _airTemp(aT){
 }
Member Function Documentation
getAirTemp()
float WeatherRecord::getAirTemp () const
Get the air temperature.
Returns
float The air temperature
Definition at line 85 of file WeatherRecord.cpp.
{
     return _airTemp;
 }
References _airTemp.
Referenced by Test1(), Test2(), and Test3().
getDate()
Date WeatherRecord::getDate () const
Get the date object.
Returns
Date& Reference to the Date object.
Definition at line 29 of file WeatherRecord.cpp.
{
     return _date;
 }
References _date.
getSolarRad()
float WeatherRecord::getSolarRad () const
Get the solar radiation.
Returns
float The solar radiation in watts per square meter.
Definition at line 71 of file WeatherRecord.cpp.
{
     return _solarRad;
 }
References _solarRad.
Referenced by Test1(), Test2(), and Test3().
getSpeed()
float WeatherRecord::getSpeed () const
Get the wind speed.
Returns
float The wind speed in meters per second.
Definition at line 57 of file WeatherRecord.cpp.
{
     return _speed;
 }
References _speed.
Referenced by Test1(), Test2(), and Test3().
getTime()
Time WeatherRecord::getTime () const
Get the Time object.
Returns
Time& Reference to the Time object.
Definition at line 43 of file WeatherRecord.cpp.
{
     return _time;
 }
References _time.
setAirTemp()
void WeatherRecord::setAirTemp (float aT)
Set the air temperature.
Parameters
aT The air temperature
Returns
void
Definition at line 92 of file WeatherRecord.cpp.
{
     _airTemp = aT;
 }
References _airTemp.
Referenced by Test3().
setDate()
void WeatherRecord::setDate (Date d)
Set the Date object.
Parameters
d The Date object to set.
Returns
void
Definition at line 36 of file WeatherRecord.cpp.
{
     _date = d;
 }
References _date.
Referenced by Test3().
setSolarRad()
void WeatherRecord::setSolarRad (float sR)
Set the solar radiation.
Parameters
sR The solar radiation in watts per square meter to set.
Returns
void
Definition at line 78 of file WeatherRecord.cpp.
{
     _solarRad = sR;
 }
References _solarRad.
Referenced by Test3().
setSpeed()
void WeatherRecord::setSpeed (float s)
Set the wind speed.
Parameters
s The wind speed in meters per second to set.
Returns
void
Definition at line 64 of file WeatherRecord.cpp.
{
     _speed = s;
 }
References _speed.
Referenced by Test3().
setTime()
void WeatherRecord::setTime (Time t)
Set the Time object.
Parameters
t The Time object to set.
Returns
void
Definition at line 50 of file WeatherRecord.cpp.
{
     _time = t;
 }
References _time.
Referenced by Test3().
Member Data Documentation
_airTemp
float WeatherRecord::_airTemp private
The solar radiation.
Definition at line 127 of file WeatherRecord.h.
Referenced by getAirTemp(), and setAirTemp().
_date
Date WeatherRecord::_date private
Definition at line 123 of file WeatherRecord.h.
Referenced by getDate(), and setDate().
_solarRad
float WeatherRecord::_solarRad private
The wind speed.
Definition at line 126 of file WeatherRecord.h.
Referenced by getSolarRad(), and setSolarRad().
_speed
float WeatherRecord::_speed private
The recorded time.
Definition at line 125 of file WeatherRecord.h.
Referenced by getSpeed(), and setSpeed().
_time
Time WeatherRecord::_time private
The recorded date.
Definition at line 124 of file WeatherRecord.h.
Referenced by getTime(), and setTime().
The documentation for this class was generated from the following files:
Week 6/lab06/WeatherRecord.h
Week 6/lab06/WeatherRecord.cpp