Assignment 1: HelperFunctions.cpp File Reference
HelperFunctions.cpp File Reference
#include "HelperFunctions.h"
#include "Validator.h"
#include <iostream>
#include <string>
#include <cmath>
Functions
int readChoice ()
Contains all functions that calculate the required thing related to weather data.
int readYear ()
int readMonth ()
bool findMatches (const WeatherLog &weather_data, WeatherLog &match_data, int month, int year)
void generateArray (const WeatherLog &match_data, double *array, int mode)
double calculateAverage (const double *array, LongInt size)
double calculateSDevi (const double *array, double mean, LongInt size)
double calculateSumSquared (const double *array, double mean, LongInt size)
double calculateTotal (const double *array, LongInt size)
Function Documentation
calculateAverage()
double calculateAverage (const double * array, LongInt size)
Definition at line 148 of file HelperFunctions.cpp.
{
     double sum = calculateTotal(array, size);
     double avg = sum/size;
     return avg;
 }
References calculateTotal().
Referenced by averageAirTempHandler(), averageWindSpeedHandler(), testCalculateAverage(), testCalculateSDevi(), and testCalculateSumSquared().
calculateSDevi()
double calculateSDevi (const double * array, double mean, LongInt size)
Definition at line 160 of file HelperFunctions.cpp.
{
     double sum = calculateSumSquared(array, mean, size);
     return sqrt(sum/size);
 }
References calculateSumSquared().
Referenced by averageAirTempHandler(), averageWindSpeedHandler(), and testCalculateSDevi().
calculateSumSquared()
double calculateSumSquared (const double * array, double mean, LongInt size)
Definition at line 169 of file HelperFunctions.cpp.
{
     double sum = 0;
     for(LongInt i = 0; i < size; i++){
         sum += (array[i] - mean) * (array[i] - mean);
     }
     return sum;
 }
Referenced by calculateSDevi(), and testCalculateSumSquared().
calculateTotal()
double calculateTotal (const double * array, LongInt size)
Definition at line 182 of file HelperFunctions.cpp.
{
     double sum = 0;
     for(LongInt i = 0; i < size; i++){
         sum += array[i];
     }
     return sum;
 }
Referenced by calculateAverage(), testCalculateTotal(), and totalSolarRadiationHandler().
findMatches()
bool findMatches (const WeatherLog & weather_data, WeatherLog & match_data, int month, int year)
Definition at line 107 of file HelperFunctions.cpp.
{
     bool match = false;
     for(long long int  i = 0; i < weather_data.Size(); i++){
         if(weather_data[i].date.GetYear() == year){
             if (month == -1){
                 match_data.add(weather_data[i]);
                 match = true;
             }
             else if(weather_data[i].date.GetMonth() == month){
                 match_data.add(weather_data[i]);
                 match = true;
             }
         }
     }
     return (match);
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
generateArray()
void generateArray (const WeatherLog & match_data, double * array, int mode)
Definition at line 129 of file HelperFunctions.cpp.
{
     for(long long int i = 0; i < match_data.Size(); i++){
         // mode = 1 for WindSpeed, mode = 2 for Air Temperature, mode = 3 for Solar Radiation
         if(mode == 1){
             array[i] = match_data[i].speed*SpeedExchangeRate;
         }
         else if (mode == 2){
             array[i] = match_data[i].airTemp;
         }
         else if (mode == 3){
             array[i] = match_data[i].solarRad*RadiationExchangeRate;
         }
     }
 }
References RadiationExchangeRate, Vector< T >::Size(), and SpeedExchangeRate.
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
readChoice()
int readChoice ()
Contains all functions that calculate the required thing related to weather data.
Author
Trong Tu Le
Version
01
Definition at line 18 of file HelperFunctions.cpp.
                 {
     string choice = " ";
     bool valid = false;
     while(!valid){
         cout << "Enter your choice: " << endl;
         cin >> choice;
         valid = isValidInteger(choice);
         if(!valid){
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
             cout << "!!!Please enter a positive integer!!!" << endl;
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
         }
     }
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
     return stoi(choice);
 }
References isValidInteger().
Referenced by menu().
readMonth()
int readMonth ()
Definition at line 75 of file HelperFunctions.cpp.
                {
     string month = " ";
     bool valid = false;
     while(!valid){
         cout << "Enter a month: ";
         cin >> month;
         valid = isValidInteger(month);
         if(!valid){
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
             cout << "!!!Please enter a positive integer!!!" << endl;
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
         }
         else {
             valid = isValidMonth(stoi(month));
             if(!valid){
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
             cout << "!!!The month must be between 1 to 12!!!" << endl;
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
         }
         }
     }
     return stoi(month);
 }
References isValidInteger(), and isValidMonth().
Referenced by firstCaseHandler().
readYear()
int readYear ()
Definition at line 43 of file HelperFunctions.cpp.
               {
     string year = " ";
     bool valid = false;
     while(!valid){
         cout << "Enter a year: ";
         cin >> year;
         valid = isValidInteger(year);
         if(!valid){
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
             cout << "!!!Please enter a positive integer!!!" << endl;
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
         }
         else {
             valid = isValidYear(stoi(year));
             if(!valid){
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
             cout << "!!!The year must be between 0 to 9999!!!" << endl;
             cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
         }
         }
     }
     return stoi(year);
 }
References isValidInteger(), and isValidYear().
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().