Assignment 1: OutputFunctions.cpp File Reference
OutputFunctions.cpp File Reference
#include "OutputFunctions.h"
#include <iostream>
#include <iomanip>
Functions
void outputWindSpeed (double avg, double sd, int month, int year)
Contains all needed output functions.
void outputAirTemp (const double avgArray[], const double sdArray[], int year)
void outputSolarRad (const double totalsArray[], int year)
void outputEverything (const double avgSpeedArray[], const double speedSdArray[], const double avgAirTempArray[], const double airTempSdArray[], const double totalSolarRadArray[], int year)
Function Documentation
outputAirTemp()
void outputAirTemp (const double avgArray[], const double sdArray[], int year)
Definition at line 34 of file OutputFunctions.cpp.
{
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
     cout << year << ":" << endl;
     for(int i = 0; i < MonthCounts; i++){
         cout << MonthsNames[i] << ": ";
         if(avgArray[i] >= 0){
             cout << fixed << setprecision(1) << "average: " << avgArray[i] << " degrees C, "
                  << "stdev: " << sdArray[i] << endl;
         }
         else{
             cout << "No data" << endl;
         }
     }
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
 }
References MonthCounts, and MonthsNames.
Referenced by secondCaseHandler().
outputEverything()
void outputEverything (const double avgSpeedArray[], const double speedSdArray[], const double avgAirTempArray[], const double airTempSdArray[], const double totalSolarRadArray[], int year)
Definition at line 75 of file OutputFunctions.cpp.
{
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
     bool noDataForYear = true;
     for(int i = 0; i < MonthCounts; i++){
         if(avgSpeedArray[i] > 0 || avgAirTempArray[i] >= 0 || totalSolarRadArray[i] >= 0){
             noDataForYear = false;
             cout << MonthsNames[i] << ", ";
             if(avgSpeedArray[i] >= 0){
                 cout << fixed << setprecision(1) << avgSpeedArray[i] << "(" << speedSdArray[i] << "), ";
             }
             else{
                 cout << ", ";
             }
             if(avgAirTempArray[i] >= 0){
                 cout << fixed << setprecision(1) << avgAirTempArray[i] << "(" << airTempSdArray[i] << "), ";
             }
             else{
                 cout << ", ";
             }
             if(totalSolarRadArray[i] >= 0){
                 cout << fixed << setprecision(1) << totalSolarRadArray[i];
             }
             cout << endl;
         }
     }
     if(noDataForYear){
         cout << year << ":" << endl;
         cout << "No Data" << endl;
     }
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
 }
References MonthCounts, and MonthsNames.
Referenced by fourthCaseHandler().
outputSolarRad()
void outputSolarRad (const double totalsArray[], int year)
Definition at line 55 of file OutputFunctions.cpp.
{
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
     cout << year << ":" << endl;
     for(int i = 0; i < MonthCounts; i++){
         cout << MonthsNames[i] << ": ";
         if(totalsArray[i] >= 0){
             cout << fixed << setprecision(1) << totalsArray[i] << " kWh/m2" << endl;
         }
         else{
             cout << "No data" << endl;
         }
     }
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
 }
References MonthCounts, and MonthsNames.
Referenced by thirdCaseHandler().
outputWindSpeed()
void outputWindSpeed (double avg, double sd, int year, int month)
Contains all needed output functions.
Author
Trong Tu Le
Version
01
Definition at line 16 of file OutputFunctions.cpp.
{
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
     cout <<  MonthsNames[month-1] << " " << year << ":";
     if(avg > 0){
         cout << "\nAverage Speed: " << fixed << setprecision(1) << avg << " km/h" << '\n' <<
         "Standard deviation: " << sd << endl;
     }
     else{
         cout << " No data" << endl;
     }
     cout << "-------------------------------------------------------------------------------------------------------------------" << endl;
 }
References MonthsNames.
Referenced by firstCaseHandler().