Assignment 1: Test Programs/TestCalculateFunctions.cpp File Reference
TestCalculateFunctions.cpp File Reference
#include "../HelperFunctions.h"
#include <iostream>
#include <string>
#include <cmath>
Functions
void printResult (string testName, bool result)
int testCalculateTotal ()
int testCalculateAverage ()
int testCalculateSumSquared ()
int testCalculateSDevi ()
int main ()
Function Documentation
main()
int main ()
Definition at line 25 of file TestCalculateFunctions.cpp.
            {
     //--------------------------------------
     //Test calculateTotal
     printResult("testCalculateTotal", testCalculateTotal());
     //--------------------------------------
     //Test calculateAverage
     printResult("testCalculateAverage", testCalculateAverage());
     //--------------------------------------
     //Test calculateSumSquared
     printResult("testCalculateSumSquared", testCalculateSumSquared());
     //--------------------------------------
     //Test calculateSDevi
     printResult("testCalculateSDevi", testCalculateSDevi());
     //--------------------------------------
     cout << "All tests passed" << endl;
     return(0);
 }
References printResult(), testCalculateAverage(), testCalculateSDevi(), testCalculateSumSquared(), and testCalculateTotal().
printResult()
void printResult (string testName, bool result)
Definition at line 52 of file TestCalculateFunctions.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << "\"" << testName << "\"" << " " << stringResult << ".\n" << endl;
 }
Referenced by main().
testCalculateAverage()
int testCalculateAverage ()
Definition at line 70 of file TestCalculateFunctions.cpp.
{
     double array[] = {1.1, 2.2, 3.3, 4.4, 5.5};
     double avg = calculateAverage(array, 5);
     return (fabs(avg - 3.3) < 0.05 ? 1 : 0);
 }
References calculateAverage().
Referenced by main().
testCalculateSDevi()
int testCalculateSDevi ()
Definition at line 94 of file TestCalculateFunctions.cpp.
{
     double array[] = {1.1, 2.2, 3.3, 4.4, 5.5};
     double avg = calculateAverage(array, 5);
     double sd = calculateSDevi(array, avg, 5);
     return (fabs(sd - 1.55) < 0.05 ? 1 : 0);
 }
References calculateAverage(), and calculateSDevi().
Referenced by main().
testCalculateSumSquared()
int testCalculateSumSquared ()
Definition at line 81 of file TestCalculateFunctions.cpp.
{
     double array[] = {1.1, 2.2, 3.3, 4.4, 5.5};
     double avg = calculateAverage(array, 5);
     double sum = calculateSumSquared(array, avg, 5);
     return (fabs(sum - 12.1) < 0.05 ? 1 : 0);
 }
References calculateAverage(), and calculateSumSquared().
Referenced by main().
testCalculateTotal()
int testCalculateTotal ()
Definition at line 60 of file TestCalculateFunctions.cpp.
{
     double array[] = {1.1, 2.2, 3.3, 4.4, 5.5};
     double sum = calculateTotal(array, 5);
     return (fabs(sum - 16.5) < 0.05 ? 1 : 0);
 }
References calculateTotal().
Referenced by main().