Assignment 1: Test Programs/TestValidateFunctions.cpp File Reference
TestValidateFunctions.cpp File Reference
#include "../Validator.h"
#include <iostream>
#include <string>
Functions
void printResult (string testName, bool result)
int testIsValidInteger ()
int testIsValidYear ()
int testIsValidMonth ()
int main ()
Function Documentation
main()
int main ()
Definition at line 24 of file TestValidateFunctions.cpp.
            {
     //--------------------------------------
     //Test isValidYear
     printResult("testIsValidInteger", testIsValidInteger());
     //--------------------------------------
     //Test isValidYear
     printResult("testIsValidYear", testIsValidYear());
     //--------------------------------------
     //Test isValidMonth
     printResult("testIsValidMonth", testIsValidMonth());
     //--------------------------------------
     cout << "All tests passed" << endl;
     return(0);
 }
References printResult(), testIsValidInteger(), testIsValidMonth(), and testIsValidYear().
printResult()
void printResult (string testName, bool result)
Definition at line 47 of file TestValidateFunctions.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << "\"" << testName << "\"" << " " << stringResult << ".\n" << endl;
 }
Referenced by main().
testIsValidInteger()
int testIsValidInteger ()
Definition at line 56 of file TestValidateFunctions.cpp.
{
     string s1 = "abc";
     string s2 = "212";
     return (!isValidInteger(s1) && isValidInteger(s2) ? 1 : 0);
 }
References isValidInteger().
Referenced by main().
testIsValidMonth()
int testIsValidMonth ()
Definition at line 78 of file TestValidateFunctions.cpp.
                       {
     int m1 = 0;
     int m2 = 9;
     int m3 = 13;
     return(!isValidMonth(m1) && isValidMonth(m2) && !isValidMonth(m3) ? 1 : 0);
 }
References isValidMonth().
Referenced by main().
testIsValidYear()
int testIsValidYear ()
Definition at line 66 of file TestValidateFunctions.cpp.
                      {
     int y1 = 0;
     int y2 = -1;
     int y3 = 2914;
     int y4 = 10000;
     return(isValidYear(y1) && !isValidYear(y2) && isValidYear(y3) && !isValidYear(y4) ? 1 : 0);
 }
References isValidYear().
Referenced by main().