Assignment 2: DataProcessor.cpp File Reference
DataProcessor.cpp File Reference
#include "DataProcessor.h"
#include "Validator.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <regex>
Functions
void readData (const string &fileName, WeatherLog &weather_data)
Contains all functions that read and store the read data from data file.
Map< string, int > readHeader (ifstream &inFile)
bool isValidHeaders (const Map< string, int > &headerMap)
Vector< string > getRow (const string &row)
bool isValidCell (const string &cell)
bool readWeatherRecord (const Vector< string > &rows, const Map< string, int > &headerMap, WeatherRecord &record)
bool readDateAndTime (const string &dateTimeTemplate, Date &date, Time &time)
bool readDate (const string &dateTemplate, Date &date)
bool readTime (const string &timeTemplate, Time &time)
Function Documentation
getRow()
Vector<string> getRow (const string & row)
Definition at line 107 of file DataProcessor.cpp.
{
     Vector<string> cells;
     stringstream ss(row);
     string cell;
     while(getline(ss, cell, ',')){
         cells.add(cell);
     }
     return cells;
 }
References Vector< T >::add().
Referenced by readData().
isValidCell()
bool isValidCell (const string & cell)
Definition at line 120 of file DataProcessor.cpp.
{
     if(cell == "" || cell == "N/A"){
         return false;
     }
     else{
         return true;
     }
 }
Referenced by readData().
isValidHeaders()
bool isValidHeaders (const Map< string, int > & headerMap)
Definition at line 95 of file DataProcessor.cpp.
{
     if (headerMap.contains("WAST")||
         headerMap.contains("S") ||
         headerMap.contains("SR") ||
         headerMap.contains("T")) {
         return true;
     }
     else{
         return false;
     }
 }
References Map< K, V >::contains().
Referenced by readData().
readData()
void readData (const string & fileName, WeatherLog & weather_data)
Contains all functions that read and store the read data from data file.
Author
Trong Tu Le
Version
01
Definition at line 17 of file DataProcessor.cpp.
{
     cout << "Reading file: " << fileName << endl;
     string fullFileName = "data/" + fileName;
     ifstream inFile(fullFileName);
     if (!inFile.is_open()) {
         cout << "Error opening file: " << fileName << endl;
         return;
     }
     Map<string, int> headerMap = readHeader(inFile);
     if(!isValidHeaders(headerMap)){
         cout << "Required headers missing in file: " << fileName << endl;
         return;
     }
     string line;
     int lineRead = 0;
     int lineDrop = 0;
     while(getline(inFile, line)){
         WeatherRecord record;
         Vector<string> rows = getRow(line);
         if(isValidCell(rows[headerMap.at("WAST")]) && isValidCell(rows[headerMap.at("S")]) && isValidCell(rows[headerMap.at("SR")]) && isValidCell(rows[headerMap.at("T")])){
             if (readWeatherRecord(rows, headerMap, record)) {
                 int year = record.date.GetYear();
                 int month = record.date.GetMonth();
                 if(!weather_data[year].contains(month)){
                     weather_data[year][month] =  BST<WeatherRecord>();
                 }
                 if(!weather_data.contains(year)){
                     weather_data[year] =  Map<int, BST<WeatherRecord>>();
                 }
                 weather_data[year][month].insert(record);
                 lineRead++;
             }
             else{
                 lineDrop++;
             }
         }
         else{
             lineDrop++;
         }
     }
     inFile.close();
     cout << "<<<Data read successfully>>>" << "\n"
          << "Line Read: " << lineRead << "\n"
          << "Line Drop: " << lineDrop << "\n"
          << "-------------------------------------------------------------------------------------------------------------------"
          << endl;
 }
References Map< K, V >::at(), Map< K, V >::contains(), WeatherRecord::date, Date::GetMonth(), getRow(), Date::GetYear(), Map< K, V >::insert(), isValidCell(), isValidHeaders(), readHeader(), and readWeatherRecord().
Referenced by readFileFromSource().
readDate()
bool readDate (const string & dateTemplate, Date & date)
Definition at line 162 of file DataProcessor.cpp.
{
     istringstream ss(dateTemplate);
     int day, month, year;
     char firstDelimiter, secondDelimiter;
     if(!(ss >> day >> firstDelimiter >> month >> secondDelimiter >> year) || (firstDelimiter != '/') || (secondDelimiter != '/')){
         return false;
     }
     if(!isValidDate(day, month, year)){
         return false;
     }
     date.SetDate(day);
     date.SetMonth(month);
     date.SetYear(year);
     return true;
 }
References isValidDate(), Date::SetDate(), Date::SetMonth(), and Date::SetYear().
Referenced by readDateAndTime().
readDateAndTime()
bool readDateAndTime (const string & dateTimeTemplate, Date & date, Time & time)
Definition at line 146 of file DataProcessor.cpp.
{
     istringstream ss(dateTimeTemplate);
     string dateTemplate, timeTemplate;
     if(!(getline(ss, dateTemplate, ' ') && getline(ss, timeTemplate))){
         return false;
     }
     if(!(readDate(dateTemplate, date) && readTime(timeTemplate, time))){
         return false;
     }
     return true;
 }
References readDate(), and readTime().
Referenced by readWeatherRecord().
readHeader()
Map<string, int> readHeader (ifstream & inFile)
Definition at line 77 of file DataProcessor.cpp.
{
     Map<string, int> headerMap;
     string line;
     getline(inFile, line);
     istringstream headerStream(line);
     string header;
     int index = 0;
     while (getline(headerStream, header, ',')) {
         headerMap[header] = index;
         index++;
     }
     return headerMap;
 }
Referenced by readData().
readTime()
bool readTime (const string & timeTemplate, Time & time)
Definition at line 183 of file DataProcessor.cpp.
{
     istringstream ss(timeTemplate);
     int hour, minute;
     char delimiter;
     if(!(ss >> hour >> delimiter >> minute) || (delimiter != ':')){
         return false;
     }
     if(!isValidTime(hour, minute)){
         return false;
     }
     time.SetHour(hour);
     time.SetMinute(minute);
     return true;
 }
References isValidTime(), Time::SetHour(), and Time::SetMinute().
Referenced by readDateAndTime().
readWeatherRecord()
bool readWeatherRecord (const Vector< string > & rows, const Map< string, int > & headerMap, WeatherRecord & record)
Definition at line 129 of file DataProcessor.cpp.
{
     if(!readDateAndTime(rows[headerMap.at("WAST")], record.date, record.time)){
         return false;
     }
     try{
         record.speed = stod(rows[headerMap.at("S")]);
         record.airTemp = stod(rows[headerMap.at("SR")]);
         record.solarRad = stod(rows[headerMap.at("T")]);
     }
     catch (const invalid_argument& e){
         return false;
     }
     return true;
 }
References WeatherRecord::airTemp, Map< K, V >::at(), WeatherRecord::date, readDateAndTime(), WeatherRecord::solarRad, WeatherRecord::speed, and WeatherRecord::time.
Referenced by readData().