Assignment 2: Data Processor/DataProcessor.h File Reference
DataProcessor.h File Reference
Contains all functions that read and store the read data from a data file.
#include "../Data Structures/DataStructure.h"
#include "../Data Structures/vector.h"
#include "../Data Structures/Date.h"
#include "../Data Structures/Time.h"
#include "../Data Structures/Map.h"
#include <string>
#include <fstream>
Functions
void readData (const std::string &fileName, WeatherLog &weather_data)
Reads weather data from a file and stores it in the WeatherLog.
void readHeader (std::ifstream &inFile, Map< std::string, int > &headerMap)
Reads the header of the weather data file and fills the provided map with header names and their indices.
bool isValidHeaders (const Map< std::string, int > &headerMap)
Validates the headers of the weather data file.
bool readWeatherRecord (const std::string &line, int wastIndex, int speedIndex, int solarRadIndex, int airTempIndex, WeatherRecord &record)
Reads a weather record from a line and a header map.
bool readDateAndTime (const std::string &dateTimeTemplate, Date &date, Time &time)
Reads a date and time from a template string.
bool readDate (const std::string &dateTemplate, Date &date)
Reads a date from a template string.
bool readTime (const std::string &timeTemplate, Time &time)
Reads a time from a template string.
Detailed Description
Contains all functions that read and store the read data from a data file.
This module provides functionality to read weather data from a file, process it, and store it in the WeatherLog data structure.
Author
Trong Tu Le
Version
01
Definition in file DataProcessor.h.
Function Documentation
isValidHeaders()
bool isValidHeaders (const Map< std::string, int > & headerMap)
Validates the headers of the weather data file.
Parameters
headerMap The map containing the header names and their indices.
Returns
True if the required headers are present, false otherwise.
Definition at line 72 of file dataprocessor.cpp.
{
     return headerMap.contains("WAST") &&
            headerMap.contains("S") &&
            headerMap.contains("SR") &&
            headerMap.contains("T");
 }
References Map< K, V >::contains().
Referenced by readData(), and TestIsValidHeadersFunction().
readData()
void readData (const std::string & fileName, WeatherLog & weather_data)
Reads weather data from a file and stores it in the WeatherLog.
Parameters
fileName The name of the file to read data from.
weather_data The WeatherLog to store the weather records.
Definition at line 9 of file dataprocessor.cpp.
{
     std::cout << "Reading file: " << fileName << std::endl;
     std::string fullFileName = "data/" + fileName;
     std::ifstream inFile(fullFileName);
     if (!inFile.is_open()) {
         std::cout << "Error opening file: " << fileName << std::endl;
         return;
     }
     Map<std::string, int> headerMap;
     readHeader(inFile, headerMap);
     if (!isValidHeaders(headerMap)) {
         std::cout << "Required headers missing in file: " << fileName << std::endl;
         return;
     }
     int lineRead = 0;
     int lineDropped = 0;
     std::string line;
     WeatherRecord record;
     const int wastIndex = headerMap.at("WAST");
     const int speedIndex = headerMap.at("S");
     const int solarRadIndex = headerMap.at("SR");
     const int airTempIndex = headerMap.at("T");
     while (std::getline(inFile, line)) {
         if (readWeatherRecord(line, wastIndex, speedIndex, solarRadIndex, airTempIndex, record)) {
             weather_data[record.date.GetYear()][record.date.GetMonth()].insert(record);
             lineRead++;
         } else {
             lineDropped++;
         }
     }
     inFile.close();
     std::cout << "<<<Data read successfully>>>\n"
               << "Line Read: " << lineRead << "\n"
               << "Line Dropped: " << lineDropped << "\n"
               << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
 }
References Map< K, V >::at(), WeatherRecord::date, Date::GetMonth(), Date::GetYear(), Map< K, V >::insert(), isValidHeaders(), readHeader(), and readWeatherRecord().
Referenced by readFileFromSource(), and TestReadDataFunction().
readDate()
bool readDate (const std::string & dateTemplate, Date & date)
Reads a date from a template string.
Parameters
dateTemplate The template string containing the date.
date The Date object to store the parsed date.
Returns
True if the date was successfully read, false otherwise.
Definition at line 129 of file dataprocessor.cpp.
{
     std::istringstream ss(dateTemplate);
     int day, month, year;
     char firstDelimiter, secondDelimiter;
     if (!(ss >> day >> firstDelimiter >> month >> secondDelimiter >> year) ||
         (firstDelimiter != '/') || (secondDelimiter != '/')) {
         return false;
     }
     if (!isValidDate(day, month, year)) {
         return false;
     }
     date.SetDate(day);
     date.SetMonth(month);
     date.SetYear(year);
     return true;
 }
References isValidDate(), Date::SetDate(), Date::SetMonth(), and Date::SetYear().
Referenced by readDateAndTime(), and TestReadDateFunction().
readDateAndTime()
bool readDateAndTime (const std::string & dateTimeTemplate, Date & date, Time & time)
Reads a date and time from a template string.
Parameters
dateTimeTemplate The template string containing the date and time.
date The Date object to store the parsed date.
time The Time object to store the parsed time.
Returns
True if the date and time were successfully read, false otherwise.
Definition at line 115 of file dataprocessor.cpp.
{
     std::istringstream ss(dateTimeTemplate);
     std::string dateTemplate, timeTemplate;
     if (!(std::getline(ss, dateTemplate, ' ') && std::getline(ss, timeTemplate))) {
         return false;
     }
     return readDate(dateTemplate, date) && readTime(timeTemplate, time);
 }
References readDate(), and readTime().
Referenced by readWeatherRecord(), and TestReadDateAndTimeFunction().
readHeader()
void readHeader (std::ifstream & inFile, Map< std::string, int > & headerMap)
Reads the header of the weather data file and fills the provided map with header names and their indices.
Parameters
inFile The input file stream.
headerMap The map to store the header names and their indices.
Definition at line 56 of file dataprocessor.cpp.
{
     std::string line;
     std::getline(inFile, line);
     std::istringstream headerStream(line);
     std::string header;
     int index = 0;
     while (std::getline(headerStream, header, ',')) {
         headerMap.insert(header, index++);
     }
 }
References Map< K, V >::insert().
Referenced by readData(), and TestReadHeaderFunction().
readTime()
bool readTime (const std::string & timeTemplate, Time & time)
Reads a time from a template string.
Parameters
timeTemplate The template string containing the time.
time The Time object to store the parsed time.
Returns
True if the time was successfully read, false otherwise.
Definition at line 153 of file dataprocessor.cpp.
{
     std::istringstream ss(timeTemplate);
     int hour, minute;
     char delimiter;
     if (!(ss >> hour >> delimiter >> minute) || (delimiter != ':')) {
         return false;
     }
     if (!isValidTime(hour, minute)) {
         return false;
     }
     time.SetHour(hour);
     time.SetMinute(minute);
     return true;
 }
References isValidTime(), Time::SetHour(), and Time::SetMinute().
Referenced by readDateAndTime(), and TestReadTimeFunction().
readWeatherRecord()
bool readWeatherRecord (const std::string & line, int wastIndex, int speedIndex, int solarRadIndex, int airTempIndex, WeatherRecord & record)
Reads a weather record from a line and a header map.
Parameters
line The line from the weather data file.
wastIndex The index of the WAST header.
speedIndex The index of the speed header.
solarRadIndex The index of the solar radiation header.
airTempIndex The index of the air temperature header.
record The WeatherRecord to store the parsed data.
Returns
True if the record was successfully read, false otherwise.
Definition at line 82 of file dataprocessor.cpp.
{
     std::istringstream lineStream(line);
     std::string cell;
     int currentIndex = 0;
     while (std::getline(lineStream, cell, ',')) {
         try {
             if (currentIndex == wastIndex) {
                 if (!readDateAndTime(cell, record.date, record.time)) {
                     return false;
                 }
             }
             else if (currentIndex == speedIndex) {
                 record.speed = std::stod(cell);
             }
             else if (currentIndex == solarRadIndex) {
                 record.solarRad = std::stod(cell);
             }
             else if (currentIndex == airTempIndex) {
                 record.airTemp = std::stod(cell);
             }
         } catch (const std::invalid_argument& e) {
             return false;
         }
         currentIndex++;
     }
     return true;
 }
References WeatherRecord::airTemp, WeatherRecord::date, readDateAndTime(), WeatherRecord::solarRad, WeatherRecord::speed, and WeatherRecord::time.
Referenced by readData(), and TestReadWeatherRecordFunction().