Lab06: Week 6/lab06/FUNCTIONS.H File Reference
FUNCTIONS.H File Reference
#include "date.h"
#include "time.h"
#include "vector.h"
#include <string>
Classes
struct WindRecType
Typedefs
typedef Vector< WindRecType > WindlogType
Functions
void readCSVIntoWinddata (istream &input, WindlogType &wind_data)
void createHeaderMap (stringstream &headerStream, Vector< string > &header)
int indexOf (string headerTitle, const Vector< string > &header)
void readDateAndTime (const string &dateTime, Date &date, Time &time)
void storeDate (const string &dateTemplate, Date &date)
void storeTime (const string &timeTemplate, Time &time)
void printWindData (const WindlogType &wind_data)
double calculateAvgSpeed (const WindlogType &wind_data)
double CalSDevi (const WindlogType &wind_data, double mean)
double CalSum (const WindlogType &wind_data, double mean)
void outputAvgAndDevi (double avg, double sd)
void printMatches (const WindlogType &wind_data, double avg)
Typedef Documentation
WindlogType
typedef Vector<WindRecType> WindlogType
Definition at line 14 of file FUNCTIONS.H.
Function Documentation
calculateAvgSpeed()
double calculateAvgSpeed (const WindlogType & wind_data)
Definition at line 111 of file FUNCTIONS.CPP.
{
     double sum = 0;
     for(int i = 0; i < wind_data.size(); i++){
         sum += wind_data[i].speed;
     }
     double avgInMs = sum/wind_data.size();
     double avgInKmh = avgInMs * 3600 / 1000;
     return avgInKmh;
 }
References Vector< T >::size().
Referenced by main().
CalSDevi()
double CalSDevi (const WindlogType & wind_data, double mean)
Definition at line 125 of file FUNCTIONS.CPP.
{
     double sum = CalSum(wind_data, mean);
     return sqrt(sum/(wind_data.size()-1));
 }
References CalSum(), and Vector< T >::size().
Referenced by main().
CalSum()
double CalSum (const WindlogType & wind_data, double mean)
Definition at line 130 of file FUNCTIONS.CPP.
{
     double sum = 0;
     for(int i = 0; i < wind_data.size(); i++){
         sum += (wind_data[i].speed - mean) * (wind_data[i].speed - mean);
     }
     return sum;
 }
References Vector< T >::size().
Referenced by CalSDevi().
createHeaderMap()
void createHeaderMap (stringstream & headerStream, Vector< string > & header)
Definition at line 41 of file FUNCTIONS.CPP.
{
     string line = " ";
     while(getline(headerStream, line, ',')){
         header.add(line);
     }
 }
References Vector< T >::add().
Referenced by readCSVIntoWinddata().
indexOf()
int indexOf (string headerTitle, const Vector< string > & header)
Definition at line 48 of file FUNCTIONS.CPP.
{
     int index = -1;
     for(int i = 0; i < header.size(); i++){
         if(headerTitle == header[i]){
             index = i;
             break;
         }
     }
     return index;
 }
References Vector< T >::size().
Referenced by readCSVIntoWinddata().
outputAvgAndDevi()
void outputAvgAndDevi (double avg, double sd)
Definition at line 138 of file FUNCTIONS.CPP.
{
     cout << "Average Speed: " << avg << " km/h" << '\n' <<
         "Standard Deviation: " << sd << endl;
 }
Referenced by main().
printMatches()
void printMatches (const WindlogType & wind_data, double avg)
Definition at line 143 of file FUNCTIONS.CPP.
{
     double exchangeRate = 3.6;
     double threshold = 0.5;
     int numOfMatches = 0;
     cout << "Matches: " << endl;
     for(int i = 0; i < wind_data.size(); i++){
         if(fabs(wind_data[i].speed * exchangeRate - avg) < threshold){
             cout << (numOfMatches + 1) << ": "<< wind_data[i].d << ", "<< wind_data[i].t << ", Speed: "<< (wind_data[i].speed * exchangeRate) << " km/h"<< endl;
             numOfMatches++;
         }
     }
     if(numOfMatches == 0){
         cout << "No Match found" << endl;
     }
 }
References Vector< T >::size().
Referenced by main().
printWindData()
void printWindData (const WindlogType & wind_data)
Definition at line 103 of file FUNCTIONS.CPP.
{
     cout << "Date,Time,Speed" << endl;
     cout << "-----------------------------" << endl;
     for(int i = 0; i < wind_data.size(); i++) {
         cout << (i+1) << ":" << wind_data[i].d << ", " << wind_data[i].t << ", " << "Wind Speed:" << wind_data[i].speed << " m/s" << endl;
     }
 }
References Vector< T >::size().
readCSVIntoWinddata()
void readCSVIntoWinddata (istream & input, WindlogType & wind_data)
Definition at line 9 of file FUNCTIONS.CPP.
{
     Date date = Date();
     Time time = Time();
     float speed = 0;
     string line = "";
     getline(input, line);
     stringstream headerStream(line);
     Vector<string> header;
     createHeaderMap(headerStream, header);
     while(getline(input, line)){
         stringstream ss(line);
         Vector<string> rows(header.size());
         while(getline(ss, line, ',')){
             if(rows.size() <= header.size()){
                 rows.add(line);
             }
         }
         readDateAndTime(rows[indexOf("WAST", header)], date, time);
         speed = stof(rows[indexOf("S", header)]);
         WindRecType record = {date, time, speed};
         wind_data.add(record);
     }
     cout << "Data read successfully" << endl;
 }
References Vector< T >::add(), createHeaderMap(), indexOf(), readDateAndTime(), and Vector< T >::size().
Referenced by main().
readDateAndTime()
void readDateAndTime (const string & dateTime, Date & date, Time & time)
Definition at line 61 of file FUNCTIONS.CPP.
{
     stringstream ss(dateTime);
     string temp;
     getline(ss, temp, ' ');
     storeDate(temp, date);
     getline(ss, temp, ' ');
     storeTime(temp, time);
 }
References storeDate(), and storeTime().
Referenced by readCSVIntoWinddata().
storeDate()
void storeDate (const string & dateTemplate, Date & date)
Definition at line 72 of file FUNCTIONS.CPP.
{
     stringstream ss(dateTemplate);
     string temp = "";
     getline(ss, temp, '/');
     int d = stoi(temp);
     getline(ss, temp, '/');
     int m = stoi(temp);
     getline(ss, temp, '/');
     int y = stoi(temp);
     date = Date(d, m, y);
 }
Referenced by readDateAndTime().
storeTime()
void storeTime (const string & timeTemplate, Time & time)
Definition at line 89 of file FUNCTIONS.CPP.
{
     stringstream ss(timeTemplate);
     string temp = "";
     getline(ss, temp, ' ');
     int hour = stoi(temp);
     getline(ss, temp, ' ');
     int minute = stoi(temp);
     time = Time(hour, minute);
 }
Referenced by readDateAndTime().