Assignment 2: Data Processor/FileNameReader.cpp File Reference
FileNameReader.cpp File Reference
#include "FileNameReader.h"
#include "DataProcessor.h"
#include <iostream>
#include <fstream>
#include <string>
Functions
void readFileFromSource (const std::string &sourceFile, WeatherLog &weather_data)
Reads weather data from a file and stores it in the WeatherLog structure.
Function Documentation
readFileFromSource()
void readFileFromSource (const std::string & sourceFile, WeatherLog & weather_data)
Reads weather data from a file and stores it in the WeatherLog structure.
This function takes the name of a source file, reads the weather data from it, and stores the data in the provided WeatherLog structure.
Parameters
sourceFile The name of the file to read weather data from.
weather_data The WeatherLog structure to store the read weather data.
Definition at line 17 of file FileNameReader.cpp.
{
     std::ifstream sourceInput(sourceFile);
     if (!sourceInput) {
         std::cout << "Error opening file: " << sourceFile << std::endl;
         return;
     }
     std::string fileName;
     while (std::getline(sourceInput, fileName)) {
         readData(fileName, weather_data);
     }
     sourceInput.close();
 }
References readData().
Referenced by main(), and TestReadFileFromSourceFunction().