Assignment 2: Helper Functions/HelperFunctions.h File Reference
HelperFunctions.h File Reference
Contains all functions that calculate the required metrics related to weather data.
#include "../Data Structures/DataStructure.h"
#include "../Data Structures/vector.h"
Functions
int readChoice ()
Reads and returns the user's choice from the menu.
int readYear ()
Reads and returns the user's input for the year.
int readMonth ()
Reads and returns the user's input for the month.
double calculateAverage (const Vector< double > &array)
Calculates and returns the average of the values in the array.
double calculateStandardDeviation (const Vector< double > &array)
Calculates and returns the standard deviation of the values in the array.
double calculateSumSquared (const Vector< double > &array, double mean)
Calculates and returns the sum of squared differences from the mean.
double calculateTotal (const Vector< double > &array)
Calculates and returns the total sum of the values in the array.
double calculateCorrelationCoef (const Vector< double > &array1, const Vector< double > &array2)
Calculates and returns the correlation coefficient between two arrays.
double calculateMAD (const Vector< double > &array)
Calculates and returns the Mean Absolute Deviation (MAD) of the values in the array.
Detailed Description
Contains all functions that calculate the required metrics related to weather data.
This header defines various helper functions needed to perform calculations related to weather data, such as reading user input, calculating statistical measures, and more.
Version
01
Author
Trong Tu Le
Definition in file HelperFunctions.h.
Function Documentation
calculateAverage()
double calculateAverage (const Vector< double > & array)
Calculates and returns the average of the values in the array.
Parameters
array A vector of double values.
Returns
The average of the values in the array.
Definition at line 107 of file HelperFunctions.cpp.
{
     double sum = 0;
     for (int i = 0; i < array.Size(); i++) {
         sum += array[i];
     }
     if(array.Size() == 0){
         return 0;
     }
     else{
         return sum / array.Size();
     }
 }
References Vector< T >::Size().
Referenced by calculateCorrelationCoef(), calculateMAD(), calculateStandardDeviation(), firstCaseOutput(), outputToFileAvgSdMAD(), secondCaseOutput(), TestCalculateAverage(), and TestCalculateSumSquared().
calculateCorrelationCoef()
double calculateCorrelationCoef (const Vector< double > & array1, const Vector< double > & array2)
Calculates and returns the correlation coefficient between two arrays.
Parameters
array1 A vector of double values representing the first dataset.
array2 A vector of double values representing the second dataset.
Returns
The correlation coefficient between the two arrays.
Definition at line 165 of file HelperFunctions.cpp.
{
     if(array1.Size() != array2.Size()){
         return -1;
     }
     double array1Avg = calculateAverage(array1);
     double array2Avg = calculateAverage(array2);
     double numerator = 0;
     double sumX = 0;
     double sumY = 0;
     for(int i = 0; i < array1.Size(); i++){
         numerator += (array1[i] - array1Avg) * (array2[i] - array2Avg);
         sumX += (array1[i] - array1Avg) * (array1[i] - array1Avg);
         sumY += (array2[i] - array2Avg) * (array2[i] - array2Avg);
     }
     double denominator = sqrt(sumX * sumY);
     return numerator/denominator;
 }
References calculateAverage(), and Vector< T >::Size().
Referenced by TestCalculateCorrelationCoef(), and thirdCaseHandler().
calculateMAD()
double calculateMAD (const Vector< double > & array)
Calculates and returns the Mean Absolute Deviation (MAD) of the values in the array.
Parameters
array A vector of double values.
Returns
The Mean Absolute Deviation of the values in the array.
Definition at line 190 of file HelperFunctions.cpp.
{
     double avg = calculateAverage(array);
     double sum = 0;
     for(int i = 0; i < array.Size(); i++){
         sum += fabs(array[i] - avg);
     }
     return sum/array.Size();
 }
References calculateAverage(), and Vector< T >::Size().
Referenced by outputToFileAvgSdMAD(), and TestCalculateMAD().
calculateStandardDeviation()
double calculateStandardDeviation (const Vector< double > & array)
Calculates and returns the standard deviation of the values in the array.
Parameters
array A vector of double values.
Returns
The standard deviation of the values in the array.
Definition at line 124 of file HelperFunctions.cpp.
{
     double mean = calculateAverage(array);
     double sum = calculateSumSquared(array, mean);
     if(array.Size() == 0){
         return 0;
     }
     else{
         return sqrt(sum / array.Size());
     }
 }
References calculateAverage(), calculateSumSquared(), and Vector< T >::Size().
Referenced by firstCaseOutput(), outputToFileAvgSdMAD(), secondCaseOutput(), and TestCalculateStandardDeviation().
calculateSumSquared()
double calculateSumSquared (const Vector< double > & array, double mean)
Calculates and returns the sum of squared differences from the mean.
Parameters
array A vector of double values.
mean The mean of the values in the array.
Returns
The sum of squared differences from the mean.
Definition at line 139 of file HelperFunctions.cpp.
{
     double sum = 0;
     for(LongInt i = 0; i < array.Size(); i++){
         sum += (array[i] - mean) * (array[i] - mean);
     }
     return sum;
 }
References Vector< T >::Size().
Referenced by calculateStandardDeviation(), and TestCalculateSumSquared().
calculateTotal()
double calculateTotal (const Vector< double > & array)
Calculates and returns the total sum of the values in the array.
Parameters
array A vector of double values.
Returns
The total sum of the values in the array.
Definition at line 152 of file HelperFunctions.cpp.
{
     double sum = 0;
     for(LongInt i = 0; i < array.Size(); i++){
         sum += array[i];
     }
     return sum;
 }
References Vector< T >::Size().
Referenced by fourthCaseOutput(), and TestCalculateTotal().
readChoice()
int readChoice ()
Reads and returns the user's choice from the menu.
Returns
The user's menu choice as an integer.
Definition at line 17 of file HelperFunctions.cpp.
                 {
     std::string choice = " ";
     bool valid = false;
     while(!valid){
         std::cout << "Enter your choice: " << std::endl;
         std::cin >> choice;
         valid = isValidNumber(choice);
         if(!valid){
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             std::cout << "!!!Please enter a positive integer!!!" << std::endl;
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
         }
     }
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     return stoi(choice);
 }
References isValidNumber().
Referenced by menu().
readMonth()
int readMonth ()
Reads and returns the user's input for the month.
Returns
The month entered by the user as an integer.
Definition at line 74 of file HelperFunctions.cpp.
                {
     std::string month = " ";
     bool valid = false;
     while(!valid){
         std::cout << "Enter a month: ";
         std::cin >> month;
         valid = isValidNumber(month);
         if(!valid){
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             std::cout << "!!!Please enter a positive integer!!!" << std::endl;
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
         }
         else {
             valid = isValidMonth(stoi(month));
             if(!valid){
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             std::cout << "!!!The month must be between 1 to 12!!!" << std::endl;
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             }
         }
     }
     return stoi(month);
 }
References isValidMonth(), and isValidNumber().
Referenced by firstCaseHandler(), and thirdCaseHandler().
readYear()
int readYear ()
Reads and returns the user's input for the year.
Returns
The year entered by the user as an integer.
Definition at line 42 of file HelperFunctions.cpp.
               {
     std::string year = " ";
     bool valid = false;
     while(!valid){
         std::cout << "Enter a year: ";
         std::cin >> year;
         valid = isValidNumber(year);
         if(!valid){
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             std::cout << "!!!Please enter a positive integer!!!" << std::endl;
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
         }
         else {
             valid = isValidYear(stoi(year));
             if(!valid){
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             std::cout << "!!!The year must be between 0 to 9999!!!" << std::endl;
             std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
         }
         }
     }
     return stoi(year);
 }
References isValidNumber(), and isValidYear().
Referenced by firstCaseHandler(), fourthCaseHandler(), and secondCaseHandler().