Assignment 1: IO.CPP File Reference
IO.CPP File Reference
#include "io.h"
#include "time.h"
#include "date.h"
#include <iostream>
#include <sstream>
#include <string>
#include <iomanip>
Functions
istream & operator>> (istream &input, Date &D)
Contains input/output operators of all classes.
ostream & operator<< (ostream &os, const Date &D)
istream & operator>> (istream &input, Time &T)
ostream & operator<< (ostream &os, const Time &T)
Function Documentation
operator<<() [1/2]
ostream& operator<< (ostream & os, const Date & D)
Definition at line 44 of file IO.CPP.
{
     os << "Date: " << D.GetDate() << " "
        << MonthsNames[D.GetMonth() - 1] << " " << D.GetYear();
     return os;
 }
References Date::GetDate(), Date::GetMonth(), Date::GetYear(), and MonthsNames.
operator<<() [2/2]
ostream& operator<< (ostream & os, const Time & T)
Definition at line 74 of file IO.CPP.
{
     os << "Time: " << setfill('0') << setw(2) << T.GetHour() << ":" << setfill('0') << setw(2) << T.GetMinute();
     return os;
 }
References Time::GetHour(), and Time::GetMinute().
operator>>() [1/2]
istream& operator>> (istream & input, Date & D)
Contains input/output operators of all classes.
Author
Trong Tu Le
Version
01
Definition at line 22 of file IO.CPP.
{
     string line = " ";
     getline(input, line);
     stringstream ss(line);
     string temp = " ";
     getline(ss, temp, '/');
     D.SetDate(stoi(temp));
     getline(ss, temp, '/');
     D.SetMonth(stoi(temp));
     getline(ss, temp, '/');
     D.SetYear(stoi(temp));
     return input;
 }
References Date::SetDate(), Date::SetMonth(), and Date::SetYear().
operator>>() [2/2]
istream& operator>> (istream & input, Time & T)
Definition at line 55 of file IO.CPP.
{
     string line = " ";
     getline(input, line);
     stringstream ss(line);
     string temp = " ";
     getline(ss, temp, ':');
     T.SetHour(stoi(temp));
     getline(ss, temp, ':');
     T.SetMinute(stoi(temp));
     return input;
 }
References Time::SetHour(), and Time::SetMinute().