Assignment 2: Menu Functions/MenuFunctions.h File Reference
MenuFunctions.h File Reference
Contains all menu-related functions including displaying the menu, handling choices, etc.
#include "../Data Structures/DataStructure.h"
#include "../Data Structures/vector.h"
#include <fstream>
Functions
void menu (const WeatherLog &weather_data)
Displays the menu and processes user choices.
void showMenu ()
Displays the menu options.
bool processChoice (const WeatherLog &weather_data, int choice)
Processes the user's choice from the menu.
void firstCaseHandler (const WeatherLog &weather_data)
Handles the first case from the menu.
void accumulateSpeed (Vector< double > &windSpeeds, const Vector< WeatherRecord > &data)
Accumulates wind speed data from weather records.
void firstCaseOutput (const Vector< double > &windSpeeds, int month, int year)
Outputs the wind speed data for a specific month and year.
void secondCaseHandler (const WeatherLog &weather_data)
Handles the second case from the menu.
void accumulateAirTemp (Vector< double > &temperatures, const Vector< WeatherRecord > &data)
Accumulates air temperature data from weather records.
void secondCaseOutput (const Vector< double > &temperatures, int month)
Outputs the temperature data for a specific month.
void thirdCaseHandler (const WeatherLog &weather_data)
Handles the third case from the menu.
void accumulateSolarRad (Vector< double > &solarRads, const Vector< WeatherRecord > &data)
Accumulates solar radiation data from weather records.
void fourthCaseHandler (const WeatherLog &weather_data)
Handles the fourth case from the menu.
void fourthCaseOutput (std::ofstream &outFile, const Vector< double > &windSpeeds, const Vector< double > &temperatures, const Vector< double > &solarRadiations, int month)
Outputs the weather data to a file for a specific month.
void outputToFileAvgSdMAD (std::ofstream &outFile, const Vector< double > &array)
Outputs the average, standard deviation, and mean absolute deviation of a vector to a file.
Detailed Description
Contains all menu-related functions including displaying the menu, handling choices, etc.
This file provides functions to interact with the user through a menu interface, process their choices, and handle specific cases related to weather data.
Version
01
Author
Trong Tu Le
Definition in file MenuFunctions.h.
Function Documentation
accumulateAirTemp()
void accumulateAirTemp (Vector< double > & temperatures, const Vector< WeatherRecord > & data)
Accumulates air temperature data from weather records.
Parameters
temperatures Vector to store accumulated air temperature data.
data Vector of WeatherRecord objects.
Definition at line 144 of file MenuFunctions.cpp.
{
     for(LongInt i = 0; i < data.Size(); i++){
         temperatures.add(data[i].airTemp);
     }
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
accumulateSolarRad()
void accumulateSolarRad (Vector< double > & solarRads, const Vector< WeatherRecord > & data)
Accumulates solar radiation data from weather records.
Parameters
solarRads Vector to store accumulated solar radiation data.
data Vector of WeatherRecord objects.
Definition at line 196 of file MenuFunctions.cpp.
{
     for(LongInt i = 0; i < data.Size(); i++){
         solarRads.add(data[i].solarRad*RadiationExchangeRate);
     }
 }
References Vector< T >::add(), RadiationExchangeRate, and Vector< T >::Size().
Referenced by fourthCaseHandler(), and thirdCaseHandler().
accumulateSpeed()
void accumulateSpeed (Vector< double > & windSpeeds, const Vector< WeatherRecord > & data)
Accumulates wind speed data from weather records.
Parameters
windSpeeds Vector to store accumulated wind speed data.
data Vector of WeatherRecord objects.
Definition at line 93 of file MenuFunctions.cpp.
{
     for(LongInt i = 0; i < data.Size(); i++){
         windSpeeds.add(data[i].speed*SpeedExchangeRate);
     }
 }
References Vector< T >::add(), Vector< T >::Size(), and SpeedExchangeRate.
Referenced by firstCaseHandler(), fourthCaseHandler(), and thirdCaseHandler().
firstCaseHandler()
void firstCaseHandler (const WeatherLog & weather_data)
Handles the first case from the menu.
This function processes wind speed data for a specific month and year.
Parameters
weather_data The WeatherLog object containing weather records.
Definition at line 72 of file MenuFunctions.cpp.
{
     int year = readYear();
     int month = readMonth();
     Vector<double> windSpeeds;
     if (weather_data.contains(year) && weather_data.at(year).contains(month)) {
         weather_data.at(year).at(month).inOrder(DataCollector::accumulateData);
         accumulateSpeed(windSpeeds, DataCollector::getData());
     }
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     firstCaseOutput(windSpeeds, month, year);
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     DataCollector::clear();
 }
References DataCollector::accumulateData(), accumulateSpeed(), Map< K, V >::at(), DataCollector::clear(), Map< K, V >::contains(), firstCaseOutput(), DataCollector::getData(), readMonth(), and readYear().
Referenced by processChoice(), and testFirstCaseHandler().
firstCaseOutput()
void firstCaseOutput (const Vector< double > & windSpeeds, int month, int year)
Outputs the wind speed data for a specific month and year.
Parameters
windSpeeds A vector containing the wind speed data.
month The month for which the data is output.
year The year for which the data is output.
Definition at line 102 of file MenuFunctions.cpp.
{
     if (windSpeeds.Size() == 0) {
         outputWindSpeed(0, 0, month, year);
     } else {
         double average = calculateAverage(windSpeeds);
         double stdev = calculateStandardDeviation(windSpeeds);
         outputWindSpeed(average, stdev, month, year);
     }
 }
References calculateAverage(), calculateStandardDeviation(), outputWindSpeed(), and Vector< T >::Size().
Referenced by firstCaseHandler().
fourthCaseHandler()
void fourthCaseHandler (const WeatherLog & weather_data)
Handles the fourth case from the menu.
This function processes and outputs multiple types of weather data for a specific month.
Parameters
weather_data The WeatherLog object containing weather records.
Definition at line 205 of file MenuFunctions.cpp.
{
     int year = readYear();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     std::ofstream outFile("WindTempSolar.csv");
     if (!outFile) {
         std::cout << "Error creating file: WindTempSolar.csv" << std::endl;
         std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
         return;
     }
     outFile << year << std::endl;
     if (weather_data.contains(year)) {
         Vector<double> windSpeeds, temperatures, solarRads;
         for (int month = 1; month <= MonthCounts; month++) {
             if (weather_data.at(year).contains(month)) {
                 weather_data.at(year).at(month).inOrder(DataCollector::accumulateData);
                 accumulateSpeed(windSpeeds, DataCollector::getData());
                 accumulateAirTemp(temperatures, DataCollector::getData());
                 accumulateSolarRad(solarRads, DataCollector::getData());
             }
             fourthCaseOutput(outFile, windSpeeds, temperatures, solarRads, month);
             DataCollector::clear();
             windSpeeds.Clear();
             temperatures.Clear();
             solarRads.Clear();
         }
     } else {
         outFile << "No data" << std::endl;
     }
     std::cout << "Write Data to WindTempSolar.csv Successfully" << std::endl;
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     outFile.close();
     DataCollector::clear();
 }
References accumulateAirTemp(), DataCollector::accumulateData(), accumulateSolarRad(), accumulateSpeed(), Map< K, V >::at(), DataCollector::clear(), Vector< T >::Clear(), Map< K, V >::contains(), fourthCaseOutput(), DataCollector::getData(), MonthCounts, and readYear().
Referenced by processChoice(), and testFourthCaseHandler().
fourthCaseOutput()
void fourthCaseOutput (std::ofstream & outFile, const Vector< double > & windSpeeds, const Vector< double > & temperatures, const Vector< double > & solarRadiations, int month)
Outputs the weather data to a file for a specific month.
Parameters
outFile The output file stream.
windSpeeds A vector containing the wind speed data.
temperatures A vector containing the temperature data.
solarRadiations A vector containing the solar radiation data.
month The month for which the data is output.
Definition at line 248 of file MenuFunctions.cpp.
{
     if (!(windSpeeds.Size() == 0 && temperatures.Size() == 0 && solarRadiations.Size() == 0)) {
         outFile << MonthsNames[month - 1] << "," << std::fixed << std::setprecision(1);
         outputToFileAvgSdMAD(outFile, windSpeeds);
         outputToFileAvgSdMAD(outFile, temperatures);
         if (solarRadiations.Size() != 0) {
             double totalRadiation = calculateTotal(solarRadiations);
             outFile << totalRadiation << std::endl;
         } else {
             outFile << "," << std::endl;
         }
     }
 }
References calculateTotal(), MonthsNames, outputToFileAvgSdMAD(), and Vector< T >::Size().
Referenced by fourthCaseHandler().
menu()
void menu (const WeatherLog & weather_data)
Displays the menu and processes user choices.
Parameters
weather_data The WeatherLog object containing weather records.
Definition at line 18 of file MenuFunctions.cpp.
{
     bool exit = false;
     while (!exit) {
         showMenu();
         int choice = readChoice();
         exit = processChoice(weather_data, choice);
     }
 }
References processChoice(), readChoice(), and showMenu().
Referenced by main(), and testMenu().
outputToFileAvgSdMAD()
void outputToFileAvgSdMAD (std::ofstream & outFile, const Vector< double > & array)
Outputs the average, standard deviation, and mean absolute deviation of a vector to a file.
Parameters
outFile The output file stream.
array A vector containing the data.
Definition at line 267 of file MenuFunctions.cpp.
{
     if (array.Size() != 0) {
         double avg = calculateAverage(array);
         double stdev = calculateStandardDeviation(array);
         double mad = calculateMAD(array);
         outFile << "\"" << avg << "(" << stdev << ", " << mad << ")\",";
     } else {
         outFile << ",";
     }
 }
References calculateAverage(), calculateMAD(), calculateStandardDeviation(), and Vector< T >::Size().
Referenced by fourthCaseOutput().
processChoice()
bool processChoice (const WeatherLog & weather_data, int choice)
Processes the user's choice from the menu.
Parameters
weather_data The WeatherLog object containing weather records.
choice The user's choice as an integer.
Returns
true if the choice was processed successfully.
false if the choice was invalid or indicated an exit.
Definition at line 45 of file MenuFunctions.cpp.
{
     switch (choice) {
         case 1:
             firstCaseHandler(weather_data);
             return false;
         case 2:
             secondCaseHandler(weather_data);
             return false;
         case 3:
             thirdCaseHandler(weather_data);
             return false;
         case 4:
             fourthCaseHandler(weather_data);
             return false;
         case 5:
             std::cout << "Exiting the program..." << std::endl;
             return true;
         default:
             std::cout << "Invalid choice. Please enter a choice from 1 to 5!\n"
                       << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
             return false;
     }
 }
References firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
Referenced by menu().
secondCaseHandler()
void secondCaseHandler (const WeatherLog & weather_data)
Handles the second case from the menu.
This function processes temperature data for a specific month and year.
Parameters
weather_data The WeatherLog object containing weather records.
Definition at line 115 of file MenuFunctions.cpp.
{
     int year = readYear();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     std::cout << year << ":" << std::endl;
     if (weather_data.contains(year)) {
         Vector<double> temperatures;
         for (int month = 1; month <= MonthCounts; month++) {
             if (weather_data.at(year).contains(month)) {
                 weather_data.at(year).at(month).inOrder(DataCollector::accumulateData);
                 accumulateAirTemp(temperatures, DataCollector::getData());
             }
             secondCaseOutput(temperatures, month);
             DataCollector::clear();
             temperatures.Clear();
         }
     } else {
         std::cout << "No data" << std::endl;
     }
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     DataCollector::clear();
 }
References accumulateAirTemp(), DataCollector::accumulateData(), Map< K, V >::at(), DataCollector::clear(), Vector< T >::Clear(), Map< K, V >::contains(), DataCollector::getData(), MonthCounts, readYear(), and secondCaseOutput().
Referenced by processChoice(), and testSecondCaseHandler().
secondCaseOutput()
void secondCaseOutput (const Vector< double > & temperatures, int month)
Outputs the temperature data for a specific month.
Parameters
temperatures A vector containing the air temperature data.
month The month for which the data is output.
Definition at line 153 of file MenuFunctions.cpp.
{
     if (temperatures.Size() == 0) {
         outputAirTemp(0, 0, month);
     } else {
         double average = calculateAverage(temperatures);
         double stdev = calculateStandardDeviation(temperatures);
         outputAirTemp(average, stdev, month);
     }
 }
References calculateAverage(), calculateStandardDeviation(), outputAirTemp(), and Vector< T >::Size().
Referenced by secondCaseHandler().
showMenu()
void showMenu ()
Displays the menu options.
Definition at line 31 of file MenuFunctions.cpp.
                 {
     std::cout << "Menu: Type(\n"
               << "1 : Display Average Wind Speed And Sample Standard Deviation In A Month Of A Year.\n"
               << "2 : Display Average Ambient Air Temperature And Sample Standard Deviation For Each Month Of A Year.\n"
               << "3 : Display The Correlation Coefficients of Wind Speed, Air Temperature, and Solar Radiation In A Specified Month.\n"
               << "4 : Display Average Wind Speed, Average Ambient Air Temperature, And Total Solar Radiation For Each Month Of A Year.\n"
               << "5 : Exit the program.)\n"
               << "-------------------------------------------------------------------------------------------------------------------"
               << std::endl;
 }
Referenced by menu().
thirdCaseHandler()
void thirdCaseHandler (const WeatherLog & weather_data)
Handles the third case from the menu.
This function processes solar radiation data for a specific month and year.
Parameters
weather_data The WeatherLog object containing weather records.
Definition at line 166 of file MenuFunctions.cpp.
{
     int month = readMonth();
     Vector<double> windSpeeds, temperatures, solarRads;
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     for (WeatherLog::const_iterator it = weather_data.begin(); it != weather_data.end(); ++it) {
         if (it->second.contains(month)) {
             it->second.at(month).inOrder(DataCollector::accumulateData);
             accumulateSpeed(windSpeeds, DataCollector::getData());
             accumulateAirTemp(temperatures, DataCollector::getData());
             accumulateSolarRad(solarRads, DataCollector::getData());
         }
         DataCollector::clear();
     }
     double S_T = calculateCorrelationCoef(windSpeeds, temperatures);
     double S_R = calculateCorrelationCoef(windSpeeds, solarRads);
     double T_R = calculateCorrelationCoef(temperatures, solarRads);
     outputCorrelationCoef(S_T, S_R, T_R, month);
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     DataCollector::clear();
 }
References accumulateAirTemp(), DataCollector::accumulateData(), accumulateSolarRad(), accumulateSpeed(), Map< K, V >::begin(), calculateCorrelationCoef(), DataCollector::clear(), Map< K, V >::end(), DataCollector::getData(), outputCorrelationCoef(), and readMonth().
Referenced by processChoice(), and testThirdCaseHandler().