Assignment 2: Operator/OPERATOR.H File Reference
OPERATOR.H File Reference
#include "../Data Structures/DataStructure.h"
Functions
bool operator< (const Date &lhs, const Date &rhs)
Less than operator for Date.
bool operator> (const Date &lhs, const Date &rhs)
Greater than operator for Date.
bool operator== (const Date &lhs, const Date &rhs)
Equality operator for Date.
bool operator< (const Time &lhs, const Time &rhs)
Less than operator for Time.
bool operator> (const Time &lhs, const Time &rhs)
Greater than operator for Time.
bool operator== (const Time &lhs, const Time &rhs)
Equality operator for Time.
bool operator< (const WeatherRecord &lhs, const WeatherRecord &rhs)
Less than operator for WeatherRecord.
bool operator> (const WeatherRecord &lhs, const WeatherRecord &rhs)
Greater than operator for WeatherRecord.
bool operator== (const WeatherRecord &lhs, const WeatherRecord &rhs)
Equality operator for WeatherRecord.
Function Documentation
operator<() [1/3]
bool operator< (const Date & lhs, const Date & rhs)
Less than operator for Date.
Parameters
lhs Left-hand side Date.
rhs Right-hand side Date.
Returns
true if lhs is less than rhs.
false otherwise.
Definition at line 7 of file OPERATOR.CPP.
{
     if (lhs.GetYear() < rhs.GetYear()) return true;
     if (lhs.GetMonth() > rhs.GetMonth()) return false;
     return lhs.GetDate() < rhs.GetDate();
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
operator<() [2/3]
bool operator< (const Time & lhs, const Time & rhs)
Less than operator for Time.
Parameters
lhs Left-hand side Time.
rhs Right-hand side Time.
Returns
true if lhs is less than rhs.
false otherwise.
Definition at line 35 of file OPERATOR.CPP.
{
     if(lhs.GetHour() < rhs.GetHour()) return true;
     if(lhs.GetHour() > rhs.GetHour()) return false;
     return lhs.GetMinute() < rhs.GetMinute();
 }
References Time::GetHour(), and Time::GetMinute().
operator<() [3/3]
bool operator< (const WeatherRecord & lhs, const WeatherRecord & rhs)
Less than operator for WeatherRecord.
Parameters
lhs Left-hand side WeatherRecord.
rhs Right-hand side WeatherRecord.
Returns
true if lhs is less than rhs.
false otherwise.
Definition at line 62 of file OPERATOR.CPP.
{
     if(lhs.date < rhs.date) return true;
     if(lhs.date > rhs.date) return false;
     return (lhs.time < rhs.time);
 }
References WeatherRecord::date, and WeatherRecord::time.
operator==() [1/3]
bool operator== (const Date & lhs, const Date & rhs)
Equality operator for Date.
Parameters
lhs Left-hand side Date.
rhs Right-hand side Date.
Returns
true if lhs is equal to rhs.
false otherwise.
Definition at line 25 of file OPERATOR.CPP.
{
     return lhs.GetYear() == rhs.GetYear() &&
            lhs.GetMonth() == rhs.GetMonth() &&
            lhs.GetDate() == rhs.GetDate();
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
operator==() [2/3]
bool operator== (const Time & lhs, const Time & rhs)
Equality operator for Time.
Parameters
lhs Left-hand side Time.
rhs Right-hand side Time.
Returns
true if lhs is equal to rhs.
false otherwise.
Definition at line 53 of file OPERATOR.CPP.
{
     return lhs.GetHour() == rhs.GetHour() &&
            lhs.GetMinute() == rhs.GetMinute();
 }
References Time::GetHour(), and Time::GetMinute().
operator==() [3/3]
bool operator== (const WeatherRecord & lhs, const WeatherRecord & rhs)
Equality operator for WeatherRecord.
Parameters
lhs Left-hand side WeatherRecord.
rhs Right-hand side WeatherRecord.
Returns
true if lhs is equal to rhs.
false otherwise.
Definition at line 80 of file OPERATOR.CPP.
{
     return lhs.date == rhs.date &&
            lhs.time == rhs.time;
 }
References WeatherRecord::date, and WeatherRecord::time.
operator>() [1/3]
bool operator> (const Date & lhs, const Date & rhs)
Greater than operator for Date.
Parameters
lhs Left-hand side Date.
rhs Right-hand side Date.
Returns
true if lhs is greater than rhs.
false otherwise.
Definition at line 16 of file OPERATOR.CPP.
{
     if (lhs.GetYear() > rhs.GetYear()) return true;
     if (lhs.GetMonth() < rhs.GetMonth()) return false;
     return lhs.GetDate() > rhs.GetDate();
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
operator>() [2/3]
bool operator> (const Time & lhs, const Time & rhs)
Greater than operator for Time.
Parameters
lhs Left-hand side Time.
rhs Right-hand side Time.
Returns
true if lhs is greater than rhs.
false otherwise.
Definition at line 44 of file OPERATOR.CPP.
{
     if(lhs.GetHour() > rhs.GetHour()) return true;
     if(lhs.GetHour() < rhs.GetHour()) return false;
     return lhs.GetMinute() > rhs.GetMinute();
 }
References Time::GetHour(), and Time::GetMinute().
operator>() [3/3]
bool operator> (const WeatherRecord & lhs, const WeatherRecord & rhs)
Greater than operator for WeatherRecord.
Parameters
lhs Left-hand side WeatherRecord.
rhs Right-hand side WeatherRecord.
Returns
true if lhs is greater than rhs.
false otherwise.
Definition at line 71 of file OPERATOR.CPP.
{
     if(lhs.date > rhs.date) return true;
     if(lhs.date < rhs.date) return false;
     return (lhs.time > rhs.time);
 }
References WeatherRecord::date, and WeatherRecord::time.