Assignment 2: OutputFunctions.h File Reference
OutputFunctions.h File Reference
#include "DataStructure.h"
Functions
void outputWindSpeed (double avg, double sd, int month, int year)
Contains all needed output functions.
void outputAirTemp (double avg, double sd, int month)
void outputCorrelationCoef (double s_t, double s_r, double t_r, int month)
Function Documentation
outputAirTemp()
void outputAirTemp (double avg, double sd, int month)
Definition at line 30 of file OutputFunctions.cpp.
{
     cout << MonthsNames[month-1] << ": ";
     if(avg > 0){
         cout << fixed << setprecision(1) << "average: " << avg << " degrees C, "
                 << "stdev: " << sd << endl;
     }
     else{
         cout << " No data" << endl;
     }
 }
References MonthsNames.
Referenced by secondCaseOutput().
outputCorrelationCoef()
void outputCorrelationCoef (double s_t, double s_r, double t_r, int month)
Definition at line 44 of file OutputFunctions.cpp.
{
     cout << "Sample Pearson Correlation Coeffient for " << MonthsNames[month-1] << ": " << endl;
     cout << "S_T: " << fixed << setprecision(2) << s_t << endl;
     cout << "S_R: " << s_r << endl;
     cout << "T_R: " << t_r << endl;
 }
References MonthsNames.
Referenced by thirdCaseHandler().
outputWindSpeed()
void outputWindSpeed (double avg, double sd, int month, int year)
Contains all needed output functions.
Author
Trong Tu Le
Version
01
Definition at line 14 of file OutputFunctions.cpp.
{
     cout <<  MonthsNames[month-1] << " " << year << ":";
     if(avg > 0){
         cout << "\nAverage Speed: " << fixed << setprecision(1) << avg << " km/h" << '\n' <<
         "Standard deviation: " << sd << endl;
     }
     else{
         cout << " No data" << endl;
     }
 }
References MonthsNames.
Referenced by firstCaseOutput().