Assignment 2: Test Programs/TestHelperFunctions/TestHelperFunctions.cpp File Reference
TestHelperFunctions.cpp File Reference
#include <iostream>
#include "../../Data Structures/Vector.h"
#include "../../Helper Functions/HelperFunctions.h"
#include "../../Helper Functions/HelperFunctions.cpp"
#include "../../Helper Functions/Validator.h"
#include "../../Helper Functions/Validator.cpp"
Functions
void TestCalculateAverage ()
void TestCalculateStandardDeviation ()
void TestCalculateSumSquared ()
void TestCalculateTotal ()
void TestCalculateCorrelationCoef ()
void TestCalculateMAD ()
int main ()
Function Documentation
main()
int main ()
Definition at line 81 of file TestHelperFunctions.cpp.
            {
     TestCalculateAverage();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestCalculateStandardDeviation();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestCalculateSumSquared();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestCalculateTotal();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestCalculateCorrelationCoef();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestCalculateMAD();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     std::cout << "All tests completed" << std::endl;
     return 0;
 }
References TestCalculateAverage(), TestCalculateCorrelationCoef(), TestCalculateMAD(), TestCalculateStandardDeviation(), TestCalculateSumSquared(), and TestCalculateTotal().
TestCalculateAverage()
void TestCalculateAverage ()
Definition at line 8 of file TestHelperFunctions.cpp.
{
     Vector<double> array;
     array.add(1.0);
     array.add(2.0);
     array.add(3.0);
     array.add(4.0);
     array.add(5.0);
     std::cout << "Testing calculateAverage function:" << std::endl;
     std::cout << "Expected: 3.0, Actual: " << calculateAverage(array) << std::endl;
 }
References Vector< T >::add(), and calculateAverage().
Referenced by main().
TestCalculateCorrelationCoef()
void TestCalculateCorrelationCoef ()
Definition at line 53 of file TestHelperFunctions.cpp.
{
     Vector<double> array1;
     array1.add(1.0);
     array1.add(2.0);
     array1.add(3.0);
     array1.add(4.0);
     array1.add(5.0);
     Vector<double> array2;
     array2.add(2.0);
     array2.add(4.0);
     array2.add(6.0);
     array2.add(8.0);
     array2.add(10.0);
     std::cout << "Testing calculateCorrelationCoef function:" << std::endl;
     std::cout << "Expected: 1.0, Actual: " << calculateCorrelationCoef(array1, array2) << std::endl;  // Perfect positive correlation
 }
References Vector< T >::add(), and calculateCorrelationCoef().
Referenced by main().
TestCalculateMAD()
void TestCalculateMAD ()
Definition at line 70 of file TestHelperFunctions.cpp.
{
     Vector<double> array;
     array.add(1.0);
     array.add(2.0);
     array.add(3.0);
     array.add(4.0);
     array.add(5.0);
     std::cout << "Testing calculateMAD function:" << std::endl;
     std::cout << "Expected: 1.2, Actual: " << calculateMAD(array) << std::endl;
 }
References Vector< T >::add(), and calculateMAD().
Referenced by main().
TestCalculateStandardDeviation()
void TestCalculateStandardDeviation ()
Definition at line 19 of file TestHelperFunctions.cpp.
{
     Vector<double> array;
     array.add(1.0);
     array.add(2.0);
     array.add(3.0);
     array.add(4.0);
     array.add(5.0);
     std::cout << "Testing calculateStandardDeviation function:" << std::endl;
     std::cout << "Expected: 1.41421, Actual: " << calculateStandardDeviation(array) << std::endl;  // Approximation
 }
References Vector< T >::add(), and calculateStandardDeviation().
Referenced by main().
TestCalculateSumSquared()
void TestCalculateSumSquared ()
Definition at line 30 of file TestHelperFunctions.cpp.
{
     Vector<double> array;
     array.add(1.0);
     array.add(2.0);
     array.add(3.0);
     array.add(4.0);
     array.add(5.0);
     double mean = calculateAverage(array);
     std::cout << "Testing calculateSumSquared function:" << std::endl;
     std::cout << "Expected: 10.0, Actual: " << calculateSumSquared(array, mean) << std::endl;
 }
References Vector< T >::add(), calculateAverage(), and calculateSumSquared().
Referenced by main().
TestCalculateTotal()
void TestCalculateTotal ()
Definition at line 42 of file TestHelperFunctions.cpp.
{
     Vector<double> array;
     array.add(1.0);
     array.add(2.0);
     array.add(3.0);
     array.add(4.0);
     array.add(5.0);
     std::cout << "Testing calculateTotal function:" << std::endl;
     std::cout << "Expected: 15.0, Actual: " << calculateTotal(array) << std::endl;
 }
References Vector< T >::add(), and calculateTotal().
Referenced by main().