Assignment 2: Test Programs/TestTime.cpp File Reference
TestTime.cpp File Reference
#include "../time.h"
#include <iostream>
Functions
void printResult (string testName, bool result)
int Test1 ()
int Test2 ()
int Test3 ()
int Test4 ()
int main ()
Function Documentation
main()
int main ()
Definition at line 25 of file TestTime.cpp.
           {
     printResult("Test 1", Test1()); // Test the default constructor
     printResult("Test 2", Test2()); // Test the constructor with hour and minute
     printResult("Test 3", Test3()); // Test Setters
     printResult("Test 4", Test4()); // Test Getters
     cout << "All passed" << endl;
     return(0);
 }
References printResult(), Test1(), Test2(), Test3(), and Test4().
printResult()
void printResult (string testName, bool result)
Definition at line 40 of file TestTime.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << "\"" << testName << "\"" << " " << stringResult << ".\n" << endl;
 }
Referenced by main().
Test1()
int Test1 ()
Definition at line 49 of file TestTime.cpp.
            {
     Time t1;
     return ((t1.GetHour() == 0 && t1.GetMinute() == 0) ? 1 : 0);
 }
References Time::GetHour(), and Time::GetMinute().
Referenced by main().
Test2()
int Test2 ()
Definition at line 58 of file TestTime.cpp.
            {
     Time t2(12, 34);
     return ((t2.GetHour() == 12 && t2.GetMinute() == 34) ? 1 : 0);
 }
References Time::GetHour(), and Time::GetMinute().
Referenced by main().
Test3()
int Test3 ()
Definition at line 67 of file TestTime.cpp.
            {
     Time t3;
     t3.SetHour(12);
     t3.SetMinute(59);
     return ((t3.GetHour() == 12 && t3.GetMinute() == 59) ? 1 : 0);
 }
References Time::GetHour(), Time::GetMinute(), Time::SetHour(), and Time::SetMinute().
Referenced by main().
Test4()
int Test4 ()
Definition at line 79 of file TestTime.cpp.
            {
     Time t4(9, 8);
     return ((t4.GetHour() == 9 && t4.GetMinute() == 8) ? 1 : 0);
 }
References Time::GetHour(), and Time::GetMinute().
Referenced by main().