Assignment 2: Test Programs/TestValidateFunctions/TestValidatetFunctions.cpp File Reference
TestValidatetFunctions.cpp File Reference
#include <iostream>
#include "../../Helper Functions/Validator.h"
#include "../../Helper Functions/Validator.cpp"
Functions
void TestIsValidNumberFunction ()
void TestIsValidDateFunction ()
void TestIsValidYearFunction ()
void TestIsValidMonthFunction ()
void TestIsValidTimeFunction ()
int main ()
Function Documentation
main()
int main ()
Definition at line 45 of file TestValidatetFunctions.cpp.
            {
     TestIsValidNumberFunction();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestIsValidDateFunction();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestIsValidYearFunction();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestIsValidMonthFunction();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     TestIsValidTimeFunction();
     std::cout << "-------------------------------------------------------------------------------------------------------------------" << std::endl;
     std::cout << "All tests completed" << std::endl;
     return 0;
 }
References TestIsValidDateFunction(), TestIsValidMonthFunction(), TestIsValidNumberFunction(), TestIsValidTimeFunction(), and TestIsValidYearFunction().
TestIsValidDateFunction()
void TestIsValidDateFunction ()
Definition at line 13 of file TestValidatetFunctions.cpp.
{
     std::cout << "Testing isValidDate function:" << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidDate(29, 2, 2020) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidDate(29, 2, 2019) << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidDate(31, 12, 2020) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidDate(32, 1, 2020) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidDate(0, 1, 2020) << std::endl;
 }
References isValidDate().
Referenced by main().
TestIsValidMonthFunction()
void TestIsValidMonthFunction ()
Definition at line 29 of file TestValidatetFunctions.cpp.
{
     std::cout << "Testing isValidMonth function:" << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidMonth(1) << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidMonth(12) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidMonth(0) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidMonth(13) << std::endl;
 }
References isValidMonth().
Referenced by main().
TestIsValidNumberFunction()
void TestIsValidNumberFunction ()
Definition at line 5 of file TestValidatetFunctions.cpp.
{
     std::cout << "Testing isValidNumber function:" << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidNumber("123") << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidNumber("123.45") << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidNumber("-123") << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidNumber("abc") << std::endl;
 }
References isValidNumber().
Referenced by main().
TestIsValidTimeFunction()
void TestIsValidTimeFunction ()
Definition at line 37 of file TestValidatetFunctions.cpp.
{
     std::cout << "Testing isValidTime function:" << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidTime(0, 0) << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidTime(23, 59) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidTime(24, 0) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidTime(0, 60) << std::endl;
 }
References isValidTime().
Referenced by main().
TestIsValidYearFunction()
void TestIsValidYearFunction ()
Definition at line 22 of file TestValidatetFunctions.cpp.
{
     std::cout << "Testing isValidYear function:" << std::endl;
     std::cout << "Expected: 1, Actual: " << isValidYear(2020) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidYear(0) << std::endl;
     std::cout << "Expected: 0, Actual: " << isValidYear(10000) << std::endl;
 }
References isValidYear().
Referenced by main().