Assignment 2: Test Programs/TestDate/TestDate.cpp File Reference
TestDate.cpp File Reference
#include "../../Data Structures/date.h"
#include "../../Data Structures/date.cpp"
#include <iostream>
Functions
void printResult (string testName, bool result)
int Test1 ()
int Test2 ()
int Test3 ()
int Test4 ()
int main ()
Function Documentation
main()
int main ()
Definition at line 28 of file TestDate.cpp.
           {
     printResult("Test 1", Test1()); // Test the default constructor and << operator
     printResult("Test 2", Test2()); // Test the constructor with hour and minute and << operator
     printResult("Test 3", Test3()); // Test Setters and << operator
     printResult("Test 4", Test4()); // Test Getters
     cout << "All passed" << endl;
     return(0);
 }
References printResult(), Test1(), Test2(), Test3(), and Test4().
printResult()
void printResult (string testName, bool result)
Definition at line 43 of file TestDate.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << "\"" << testName << "\"" << " " << stringResult << ".\n" << endl;
 }
References result().
Referenced by main().
Test1()
int Test1 ()
Definition at line 52 of file TestDate.cpp.
            {
     Date d1;
     return ((d1.GetDate() == 0 && d1.GetMonth() == 0 && d1.GetYear() == 0) ? 1 : 0);
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
Referenced by main().
Test2()
int Test2 ()
Definition at line 61 of file TestDate.cpp.
            {
     Date d2(18, 4, 2003);
     return ((d2.GetDate() == 18 && d2.GetMonth() == 4 && d2.GetYear() == 2003) ? 1 : 0);
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
Referenced by main().
Test3()
int Test3 ()
Definition at line 70 of file TestDate.cpp.
            {
     Date d3;
     d3.SetDate(18);
     d3.SetMonth(4);
     d3.SetYear(2003);
     return ((d3.GetDate() == 18 && d3.GetMonth() == 4 && d3.GetYear() == 2003) ? 1 : 0);
 }
References Date::GetDate(), Date::GetMonth(), Date::GetYear(), Date::SetDate(), Date::SetMonth(), and Date::SetYear().
Referenced by main().
Test4()
int Test4 ()
Definition at line 83 of file TestDate.cpp.
            {
     Date d4(12, 03, 2003);
     return ((d4.GetDate() == 12 && d4.GetMonth() == 3 && d4.GetYear() == 2003) ? 1 : 0);
 }
References Date::GetDate(), Date::GetMonth(), and Date::GetYear().
Referenced by main().