Assignment 2: Helper Functions/Validator.cpp File Reference
Validator.cpp File Reference
#include "Validator.h"
#include <regex>
Functions
bool isValidNumber (const std::string &string)
Checks if the input string represents a valid positive number.
bool isValidDate (int day, int month, int year)
Validates if the given day, month, and year form a valid date.
bool isValidYear (int year)
Validates if the given year is valid.
bool isValidMonth (int month)
Validates if the given month is valid.
bool isValidTime (int hour, int minute)
Validates if the given hour and minute form a valid time.
Function Documentation
isValidDate()
bool isValidDate (int day, int month, int year)
Validates if the given day, month, and year form a valid date.
Parameters
day The day to validate.
month The month to validate.
year The year to validate.
Returns
true if the date is valid, false otherwise.
Definition at line 22 of file Validator.cpp.
{
     if (!isValidYear(year)) return false;
     if (!isValidMonth(month)) return false;
     if (day < 1 || day > 31) return false;
     const int daysInMonth[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
     // Check for leap year
     bool isLeapYear = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
     if (isLeapYear && (month == 2)) {
         if (day <= 29) return true;
     } else {
         if (day <= daysInMonth[month - 1]) return true;
     }
     return false;
 }
References isValidMonth(), and isValidYear().
Referenced by readDate(), and TestIsValidDateFunction().
isValidMonth()
bool isValidMonth (int month)
Validates if the given month is valid.
Parameters
month The month to validate.
Returns
true if the month is valid, false otherwise.
Definition at line 54 of file Validator.cpp.
{
     if (month < 1 || month > 12) {
         return false;
     }
     return true;
 }
Referenced by isValidDate(), readMonth(), and TestIsValidMonthFunction().
isValidNumber()
bool isValidNumber (const std::string & string)
Checks if the input string represents a valid positive number.
Parameters
string The input string to validate.
Returns
true if the input string is a valid positive number, false otherwise.
Definition at line 14 of file Validator.cpp.
{
     std::regex positiveNumberPattern(R"(^\d+(\.\d+)?$)");
     return std::regex_match(string, positiveNumberPattern);
 }
Referenced by readChoice(), readMonth(), readYear(), and TestIsValidNumberFunction().
isValidTime()
bool isValidTime (int hour, int minute)
Validates if the given hour and minute form a valid time.
Parameters
hour The hour to validate.
minute The minute to validate.
Returns
true if the time is valid, false otherwise.
Definition at line 65 of file Validator.cpp.
{
     if (hour < 0 || hour > 23) return false;
     if (minute < 0 || minute > 59) return false;
     return true;
 }
Referenced by readTime(), and TestIsValidTimeFunction().
isValidYear()
bool isValidYear (int year)
Validates if the given year is valid.
Parameters
year The year to validate.
Returns
true if the year is valid, false otherwise.
Definition at line 43 of file Validator.cpp.
{
     if (year < 1 || year > 9999) {
         return false;
     }
     return true;
 }
Referenced by isValidDate(), readYear(), and TestIsValidYearFunction().