Assignment 2: Validator.h File Reference
Validator.h File Reference
#include <string>
Functions
bool isValidNumber (const string &string)
Contains all functions that do the validations of the user input.
bool isValidDate (int day, int month, int year)
bool isValidTime (int hour, int minute)
bool isValidYear (int year)
bool isValidMonth (int month)
Function Documentation
isValidDate()
bool isValidDate (int day, int month, int year)
Definition at line 20 of file Validator.cpp.
{
     if (!isValidYear(year)) return false;
     if (!isValidMonth(month)) return false;
     if (day < 1 || day > 31) return false;
     const int daysInMonth[] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
     // Check for leap year
     bool isLeapYear = (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0);
     if (isLeapYear && (month == 2)) {
         if (day <= 29) return true;
     } else {
         if (day <= daysInMonth[month - 1]) return true;
     }
     return false;
 }
References isValidMonth(), and isValidYear().
Referenced by readDate().
isValidMonth()
bool isValidMonth (int month)
Definition at line 45 of file Validator.cpp.
{
     if (month < 1 || month > 12) {
         return false;
     }
     return true;
 }
Referenced by isValidDate(), readMonth(), and testIsValidMonth().
isValidNumber()
bool isValidNumber (const string & string)
Contains all functions that do the validations of the user input.
Author
Trong Tu Le
Version
01
Definition at line 13 of file Validator.cpp.
{
     regex positiveNumberPattern(R"(^\d+(\.\d+)?$)");
     return regex_match(string, positiveNumberPattern);
 }
Referenced by readChoice(), readMonth(), and readYear().
isValidTime()
bool isValidTime (int hour, int minute)
Definition at line 53 of file Validator.cpp.
{
     if (hour < 0 || hour > 23) return false;
     if (minute < 0 || minute > 59) return false;
     return true;
 }
Referenced by readTime().
isValidYear()
bool isValidYear (int year)
Definition at line 38 of file Validator.cpp.
{
     if (year < 1 || year > 9999) {
         return false;
     }
     return true;
 }
Referenced by isValidDate(), readYear(), and testIsValidYear().