Assignment 2: SpeedCollector Class Reference
SpeedCollector Class Reference
#include <SpeedCollector.h>
Static Public Member Functions
static void accumulateSpeed (const WeatherRecord &record)
static const Vector< double > & getWindSpeeds ()
static void clear ()
static int Size ()
Static Private Attributes
static Vector< double > windSpeeds
Detailed Description
Definition at line 7 of file SpeedCollector.h.
Member Function Documentation
accumulateSpeed()
static void SpeedCollector::accumulateSpeed (const WeatherRecord & record) inline static
Definition at line 10 of file SpeedCollector.h.
{
         windSpeeds.add(record.speed * SpeedExchangeRate);
     }
References Vector< T >::add(), WeatherRecord::speed, SpeedExchangeRate, and windSpeeds.
Referenced by firstCaseHandler(), fourthCaseHandler(), and thirdCaseHandler().
clear()
static void SpeedCollector::clear () inline static
Definition at line 18 of file SpeedCollector.h.
{
         windSpeeds.Clear();
     }
References Vector< T >::Clear(), and windSpeeds.
Referenced by firstCaseHandler(), fourthCaseHandler(), and thirdCaseHandler().
getWindSpeeds()
static const Vector<double>& SpeedCollector::getWindSpeeds () inline static
Definition at line 14 of file SpeedCollector.h.
{
         return windSpeeds;
     }
References windSpeeds.
Referenced by firstCaseHandler(), fourthCaseHandler(), and thirdCaseHandler().
Size()
static int SpeedCollector::Size () inline static
Definition at line 22 of file SpeedCollector.h.
                      {
         return windSpeeds.Size();
     }
References Vector< T >::Size(), and windSpeeds.
Member Data Documentation
windSpeeds
Vector< double > SpeedCollector::windSpeeds static private
Definition at line 27 of file SpeedCollector.h.
Referenced by accumulateSpeed(), clear(), getWindSpeeds(), and Size().
The documentation for this class was generated from the following file:
SpeedCollector.h