Assignment 2: TemperatureCollector Class Reference
TemperatureCollector Class Reference
#include <TemperatureCollector.h>
Static Public Member Functions
static void accumulateAirTemp (const WeatherRecord &record)
static const Vector< double > & getTemperatures ()
static void clear ()
static int Size ()
Static Private Attributes
static Vector< double > temperatures
Detailed Description
Definition at line 8 of file TemperatureCollector.h.
Member Function Documentation
accumulateAirTemp()
static void TemperatureCollector::accumulateAirTemp (const WeatherRecord & record) inline static
Definition at line 11 of file TemperatureCollector.h.
{
         temperatures.add(record.airTemp);
     }
References Vector< T >::add(), WeatherRecord::airTemp, and temperatures.
Referenced by fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
clear()
static void TemperatureCollector::clear () inline static
Definition at line 19 of file TemperatureCollector.h.
{
         temperatures.Clear();
     }
References Vector< T >::Clear(), and temperatures.
Referenced by fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
getTemperatures()
static const Vector<double>& TemperatureCollector::getTemperatures () inline static
Definition at line 15 of file TemperatureCollector.h.
{
         return temperatures;
     }
References temperatures.
Referenced by fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
Size()
static int TemperatureCollector::Size () inline static
Definition at line 23 of file TemperatureCollector.h.
                      {
         return temperatures.Size();
     }
References Vector< T >::Size(), and temperatures.
Member Data Documentation
temperatures
Vector< double > TemperatureCollector::temperatures static private
Definition at line 28 of file TemperatureCollector.h.
Referenced by accumulateAirTemp(), clear(), getTemperatures(), and Size().
The documentation for this class was generated from the following file:
TemperatureCollector.h