Assignment 2: Time Class Reference
Time Class Reference
Represents a time with hour and minute.
#include <TIME.H>
Public Member Functions
Time ()
Default constructor. Initializes hour and minute to 0.
Time (int h, int m)
Parameterized constructor. Initializes hour and minutewith given values.
int GetHour () const
Get the hour.
void SetHour (int h)
Set the hour.
int GetMinute () const
Get the minute.
void SetMinute (int m)
Set the minute.
Private Attributes
int hour
int minute
Date.
Detailed Description
Represents a time with hour and minute.
Provides functionality to manipulate and format time.
Author
Trong Tu Le
Version
1
Definition at line 17 of file TIME.H.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
Default constructor. Initializes hour and minute to 0.
Definition at line 17 of file TIME.CPP.
            : hour(0), minute(0){
 }
Time() [2/2]
Time::Time (int h, int m)
Parameterized constructor. Initializes hour and minutewith given values.
Parameters
d Day
m Month
y Year
Definition at line 23 of file TIME.CPP.
                        : hour(h), minute(m){
 }
Member Function Documentation
GetHour()
int Time::GetHour () const
Get the hour.
Returns
int hour
Definition at line 29 of file TIME.CPP.
{
     return hour;
 }
References hour.
Referenced by operator<(), operator==(), operator>(), outputFunction(), Test1(), Test2(), Test3(), Test4(), TestReadDateAndTimeFunction(), TestReadTimeFunction(), and TestReadWeatherRecordFunction().
GetMinute()
int Time::GetMinute () const
Get the minute.
Returns
int minute
Definition at line 43 of file TIME.CPP.
{
     return minute;
 }
References minute.
Referenced by operator<(), operator==(), operator>(), outputFunction(), Test1(), Test2(), Test3(), Test4(), TestReadDateAndTimeFunction(), TestReadTimeFunction(), and TestReadWeatherRecordFunction().
SetHour()
void Time::SetHour (int h)
Set the hour.
Parameters
h - hour
Returns
void
Definition at line 36 of file TIME.CPP.
{
     hour = h;
 }
References hour.
Referenced by readTime(), and Test3().
SetMinute()
void Time::SetMinute (int m)
Set the minute.
Parameters
m - minute
Returns
void
Definition at line 50 of file TIME.CPP.
{
     minute = m;
 }
References minute.
Referenced by readTime(), and Test3().
Member Data Documentation
hour
int Time::hour private
Definition at line 64 of file TIME.H.
Referenced by GetHour(), and SetHour().
minute
int Time::minute private
Date.
Definition at line 65 of file TIME.H.
Referenced by GetMinute(), and SetMinute().
The documentation for this class was generated from the following files:
Data Structures/TIME.H
Data Structures/TIME.CPP