Assignment 2: AVL< T > Class Template Reference
AVL< T > Class Template Reference
Template class for an AVL Tree, which is a self-balancing Binary Search Tree.
#include <AVL.H>
Public Types
using funcPtr = void(*)(const T &data)
Public Member Functions
AVL ()
Function pointer type for traversal operations.
AVL (const AVL< T > &avl)
Deep copy constructor.
~AVL ()
Destructor to clean up the tree.
AVL< T > & operator= (const AVL< T > &avl)
Assignment operator to copy from another AVL Tree.
void insert (const T &data)
Insert a data value into the AVL Tree.
bool search (const T &data) const
Search for a data value in the AVL Tree.
void inOrder (const funcPtr f) const
In-order traversal of the AVL Tree.
void preOrder (const funcPtr f) const
Pre-order traversal of the AVL Tree.
void postOrder (const funcPtr f) const
Post-order traversal of the AVL Tree.
Private Member Functions
Node< T > * copyHelper (const Node< T > *node)
Root node of the AVL Tree.
void clear (Node< T > *&node)
Utility to clear the tree starting from a node.
void insertHelper (Node< T > *&node, const T &data)
Helper function to recursively insert a node and balance the tree.
bool searchHelper (const Node< T > *node, const T &data) const
Helper function to recursively search for a data value.
void inOrderHelper (const Node< T > *node, const funcPtr f) const
Helper function for in-order traversal.
void preOrderHelper (const Node< T > *node, const funcPtr f) const
Helper function for pre-order traversal.
void postOrderHelper (const Node< T > *node, const funcPtr f) const
Helper function for post-order traversal.
int height (const Node< T > *node) const
Get the height of a node.
int getBalance (const Node< T > *node) const
Get the balance factor of a node.
void rightRotate (Node< T > *&y)
Perform a right rotation on a subtree.
void leftRotate (Node< T > *&x)
Perform a left rotation on a subtree.
int max (int a, int b) const
Get the maximum of two integers.
Private Attributes
Node< T > * root
Detailed Description
template<class T>
class AVL< T >
Template class for an AVL Tree, which is a self-balancing Binary Search Tree.
Author
Trong Tu Le
Version
1 turn BST to AVL tree added function: height, getBalance, rightRotate, leftRotate, max modified function: insertHelper
Template Parameters
T Data type of the elements in the AVL Tree.
The AVL tree maintains its balance using rotations to ensure the heights of the subtrees of any node differ by at most one.
Definition at line 25 of file AVL.H.
Member Typedef Documentation
funcPtr
template<class T > using AVL< T >::funcPtr = void (*)(const T& data)
Definition at line 27 of file AVL.H.
Constructor & Destructor Documentation
AVL() [1/2]
template<class T > AVL< T >::AVL explicit
Function pointer type for traversal operations.
Default constructor for the AVL Tree.
Definition at line 176 of file AVL.H.
             : root(nullptr) {
 }
AVL() [2/2]
template<class T > AVL< T >::AVL (const AVL< T > & avl)
Deep copy constructor.
Parameters
avl The AVL Tree to copy from.
Definition at line 183 of file AVL.H.
                              : root(copyHelper(avl.root)) {
 }
~AVL()
template<class T > AVL< T >::~AVL
Destructor to clean up the tree.
Definition at line 217 of file AVL.H.
              {
     clear(this->root);
     this->root = nullptr;
 }
Referenced by testDestructor().
Member Function Documentation
clear()
template<class T > void AVL< T >::clear (Node< T > *& node) private
Utility to clear the tree starting from a node.
Parameters
node The starting node to clear from.
Definition at line 226 of file AVL.H.
{
     if (node != nullptr) {
         clear(node->left);
         clear(node->right);
         delete node;
     }
 }
References Node< T >::left, and Node< T >::right.
copyHelper()
template<class T > Node< T > * AVL< T >::copyHelper (const Node< T > * node) private
Root node of the AVL Tree.
Helper function to recursively copy nodes.
Parameters
node The node to copy from.
Returns
Pointer to the copied node.
Definition at line 190 of file AVL.H.
{
     if (node == nullptr) {
         return nullptr;
     } else {
         Node<T>* copy = new Node<T>(node->data);
         copy->left = copyHelper(node->left);
         copy->right = copyHelper(node->right);
         return copy;
     }
 }
References Node< T >::data, Node< T >::left, and Node< T >::right.
getBalance()
template<class T > int AVL< T >::getBalance (const Node< T > * node) const private
Get the balance factor of a node.
Parameters
node Node to get the balance factor of.
Returns
Balance factor of the node.
Definition at line 384 of file AVL.H.
{
     return (node == nullptr) ? 0 : height(node->left) - height(node->right);
 }
References Node< T >::left, and Node< T >::right.
height()
template<class T > int AVL< T >::height (const Node< T > * node) const private
Get the height of a node.
Parameters
node Node to get the height of.
Returns
Height of the node.
Definition at line 376 of file AVL.H.
{
     return (node == nullptr) ? 0 : node->height;
 }
References Node< T >::height.
inOrder()
template<class T > void AVL< T >::inOrder (const funcPtr f) const
In-order traversal of the AVL Tree.
Parameters
f Function pointer to be called on each node's data.
Definition at line 315 of file AVL.H.
{
     inOrderHelper(this->root, f);
 }
Referenced by testAssignOperator(), testCopyConstructor(), testDestructor(), testPassByReference(), testPassByValue(), and testTraversal().
inOrderHelper()
template<class T > void AVL< T >::inOrderHelper (const Node< T > * node, const funcPtr f) const private
Helper function for in-order traversal.
Parameters
node Root node of the current subtree.
f Function pointer to be called on each node's data.
Definition at line 323 of file AVL.H.
{
     if (node != nullptr) {
         inOrderHelper(node->left, f);
         f(node->data);
         inOrderHelper(node->right, f);
     }
 }
References Node< T >::data, Node< T >::left, and Node< T >::right.
insert()
template<class T > void AVL< T >::insert (const T & data)
Insert a data value into the AVL Tree.
Parameters
data The data value to be inserted.
Definition at line 238 of file AVL.H.
{
     insertHelper(this->root, data);
 }
Referenced by testAssignOperator(), testCopyConstructor(), testDestructor(), testInsertSearch(), testPassByReference(), testPassByValue(), testReturnByValue(), and testTraversal().
insertHelper()
template<class T > void AVL< T >::insertHelper (Node< T > *& node, const T & data) private
Helper function to recursively insert a node and balance the tree.
Parameters
node Root node of the current subtree.
data Data value to be inserted.
Definition at line 246 of file AVL.H.
{
     if (node == nullptr) {
         node = new Node<T>(data);
     }
     else if (data < node->data) {
         insertHelper(node->left, data);
     }
     else if (data > node->data) {
         insertHelper(node->right, data);
     }
     node->height = 1 + max(height(node->left), height(node->right));
     int balance = getBalance(node);
     // Left Left Case
     if (balance > 1 && data < node->left->data) {
         rightRotate(node);
     }
     // Right Right Case
     if (balance < -1 && data > node->right->data) {
         leftRotate(node);
     }
     // Left Right Case
     if (balance > 1 && data > node->left->data) {
         leftRotate(node->left);
         rightRotate(node);
     }
     // Right Left Case
     if (balance < -1 && data < node->right->data) {
         rightRotate(node->right);
         leftRotate(node);
     }
 }
References Node< T >::data, Node< T >::height, Node< T >::left, and Node< T >::right.
leftRotate()
template<class T > void AVL< T >::leftRotate (Node< T > *& x) private
Perform a left rotation on a subtree.
Parameters
x Root of the subtree to rotate.
Definition at line 409 of file AVL.H.
{
     Node<T>* y = x->right;
     Node<T>* temp = y->left;
     y->left = x;
     x->right = temp;
     x->height = max(height(x->left), height(x->right)) + 1;
     y->height = max(height(y->left), height(y->right)) + 1;
     x = y;
 }
References Node< T >::height, Node< T >::left, and Node< T >::right.
max()
template<class T > int AVL< T >::max (int a, int b) const private
Get the maximum of two integers.
Parameters
a First integer.
b Second integer.
Returns
The maximum of the two integers.
Definition at line 426 of file AVL.H.
{
     return (a > b) ? a : b;
 }
operator=()
template<class T > AVL< T > & AVL< T >::operator= (const AVL< T > & avl)
Assignment operator to copy from another AVL Tree.
Parameters
avl The AVL Tree to copy from.
Returns
Reference to the assigned AVL Tree.
Definition at line 205 of file AVL.H.
{
     if (this != &avl) {
         clear(this->root);
         this->root = copyHelper(avl.root);
     }
     return *this;
 }
References AVL< T >::root.
postOrder()
template<class T > void AVL< T >::postOrder (const funcPtr f) const
Post-order traversal of the AVL Tree.
Parameters
f Function pointer to be called on each node's data.
Definition at line 355 of file AVL.H.
{
     postOrderHelper(this->root, f);
 }
Referenced by testTraversal().
postOrderHelper()
template<class T > void AVL< T >::postOrderHelper (const Node< T > * node, const funcPtr f) const private
Helper function for post-order traversal.
Parameters
node Root node of the current subtree.
f Function pointer to be called on each node's data.
Definition at line 363 of file AVL.H.
{
     if (node != nullptr) {
         postOrderHelper(node->left, f);
         postOrderHelper(node->right, f);
         f(node->data);
     }
 }
References Node< T >::data, Node< T >::left, and Node< T >::right.
preOrder()
template<class T > void AVL< T >::preOrder (const funcPtr f) const
Pre-order traversal of the AVL Tree.
Parameters
f Function pointer to be called on each node's data.
Definition at line 335 of file AVL.H.
{
     preOrderHelper(this->root, f);
 }
Referenced by testTraversal().
preOrderHelper()
template<class T > void AVL< T >::preOrderHelper (const Node< T > * node, const funcPtr f) const private
Helper function for pre-order traversal.
Parameters
node Root node of the current subtree.
f Function pointer to be called on each node's data.
Definition at line 343 of file AVL.H.
{
     if (node != nullptr) {
         f(node->data);
         preOrderHelper(node->left, f);
         preOrderHelper(node->right, f);
     }
 }
References Node< T >::data, Node< T >::left, and Node< T >::right.
rightRotate()
template<class T > void AVL< T >::rightRotate (Node< T > *& y) private
Perform a right rotation on a subtree.
Parameters
y Root of the subtree to rotate.
Definition at line 392 of file AVL.H.
{
     Node<T>* x = y->left;
     Node<T>* temp = x->right;
     x->right = y;
     y->left = temp;
     y->height = max(height(y->left), height(y->right)) + 1;
     x->height = max(height(x->left), height(x->right)) + 1;
     y = x;
 }
References Node< T >::height, Node< T >::left, and Node< T >::right.
search()
template<class T > bool AVL< T >::search (const T & data) const
Search for a data value in the AVL Tree.
Parameters
data The data value to search for.
Returns
True if the data value is found, false otherwise.
Definition at line 288 of file AVL.H.
{
     return searchHelper(this->root, data);
 }
Referenced by testInsertSearch(), and testPassByConstReference().
searchHelper()
template<class T > bool AVL< T >::searchHelper (const Node< T > * node, const T & data) const private
Helper function to recursively search for a data value.
Parameters
node Root node of the current subtree.
data Data value to search for.
Returns
True if the data value is found, false otherwise.
Definition at line 296 of file AVL.H.
{
     if (node == nullptr) {
         return false;
     }
     else if (data == node->data) {
         return true;
     }
     else if (data < node->data) {
         return searchHelper(node->left, data);
     }
     else {
         return searchHelper(node->right, data);
     }
 }
References Node< T >::data, Node< T >::left, and Node< T >::right.
Member Data Documentation
root
template<class T > Node<T>* AVL< T >::root private
Definition at line 84 of file AVL.H.
Referenced by AVL< T >::operator=().
The documentation for this class was generated from the following file:
Data Structures/AVL.H