Assignment 2: SolarRadCollector Class Reference
SolarRadCollector Class Reference
#include <SolarRadCollector.h>
Static Public Member Functions
static void accumulateSolarRad (const WeatherRecord &record)
static const Vector< double > & getSolarRads ()
static void clear ()
static int Size ()
Static Private Attributes
static Vector< double > solarRads
Detailed Description
Definition at line 7 of file SolarRadCollector.h.
Member Function Documentation
accumulateSolarRad()
static void SolarRadCollector::accumulateSolarRad (const WeatherRecord & record) inline static
Definition at line 10 of file SolarRadCollector.h.
{
         solarRads.add(record.solarRad * RadiationExchangeRate);
     }
References Vector< T >::add(), RadiationExchangeRate, WeatherRecord::solarRad, and solarRads.
Referenced by fourthCaseHandler(), and thirdCaseHandler().
clear()
static void SolarRadCollector::clear () inline static
Definition at line 18 of file SolarRadCollector.h.
{
         solarRads.Clear();
     }
References Vector< T >::Clear(), and solarRads.
Referenced by fourthCaseHandler(), and thirdCaseHandler().
getSolarRads()
static const Vector<double>& SolarRadCollector::getSolarRads () inline static
Definition at line 14 of file SolarRadCollector.h.
{
         return solarRads;
     }
References solarRads.
Referenced by fourthCaseHandler(), and thirdCaseHandler().
Size()
static int SolarRadCollector::Size () inline static
Definition at line 22 of file SolarRadCollector.h.
                      {
         return solarRads.Size();
     }
References Vector< T >::Size(), and solarRads.
Member Data Documentation
solarRads
Vector< double > SolarRadCollector::solarRads static private
Definition at line 27 of file SolarRadCollector.h.
Referenced by accumulateSolarRad(), clear(), getSolarRads(), and Size().
The documentation for this class was generated from the following file:
SolarRadCollector.h