Assignment 2: DataCollector Class Reference
DataCollector Class Reference
#include <DataCollector.h>
Static Public Member Functions
static void accumulateData (const WeatherRecord &record)
Accumulates weather data from a weather record.
static const Vector< WeatherRecord > & getData ()
Retrieves the weather data.
static void clear ()
Clears the weather data vector.
Static Private Attributes
static Vector< WeatherRecord > data
Detailed Description
Definition at line 20 of file DataCollector.h.
Member Function Documentation
accumulateData()
void DataCollector::accumulateData (const WeatherRecord & record) static
Accumulates weather data from a weather record.
Parameters
record The weather record containing the data to be accumulated.
Definition at line 11 of file DataCollector.cpp.
{
     data.add(record);
 }
References Vector< T >::add(), and data.
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
clear()
void DataCollector::clear () static
Clears the weather data vector.
resetting the data collector.
Definition at line 25 of file DataCollector.cpp.
{
     data.Clear();
 }
References Vector< T >::Clear(), and data.
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
getData()
const Vector< WeatherRecord > & DataCollector::getData () static
Retrieves the weather data.
Returns
A constant reference to the vector of collected weather data.
Definition at line 18 of file DataCollector.cpp.
{
         return data;
 }
References data.
Referenced by firstCaseHandler(), fourthCaseHandler(), secondCaseHandler(), and thirdCaseHandler().
Member Data Documentation
data
Vector< WeatherRecord > DataCollector::data static private
Definition at line 44 of file DataCollector.h.
Referenced by accumulateData(), clear(), and getData().
The documentation for this class was generated from the following files:
Data Collectors/DataCollector.h
Data Collectors/DataCollector.cpp