Assignment 2: Date Class Reference
Date Class Reference
Represents a date including date, month and year.
#include <DATE.H>
Public Member Functions
Date ()
Default constructor. Initializes date, month, and year to 0.
Date (int d, int m, int y)
Parameterized constructor. Initializes date, month, and year with given values.
int GetDate () const
Get the day.
void SetDate (int d)
Set the day.
int GetMonth () const
Get the month.
void SetMonth (int m)
Set the month.
int GetYear () const
Get the year.
void SetYear (int y)
Set the year.
Private Attributes
int date
int month
Date.
int year
Month.
Detailed Description
Represents a date including date, month and year.
Author
Trong Tu Le
Version
01
02 remove overloaded operators
Definition at line 18 of file DATE.H.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
Default constructor. Initializes date, month, and year to 0.
Definition at line 17 of file DATE.CPP.
            : date(0), month(0), year(0){
 }
Date() [2/2]
Date::Date (int d, int m, int y)
Parameterized constructor. Initializes date, month, and year with given values.
Parameters
d Day
m Month
y Year
Definition at line 23 of file DATE.CPP.
                               : date(d), month(m), year(y){
 }
Member Function Documentation
GetDate()
int Date::GetDate () const
Get the day.
Returns
int Day
Definition at line 29 of file DATE.CPP.
{
     return date;
 }
References date.
Referenced by operator<(), operator==(), operator>(), Test1(), Test2(), Test3(), Test4(), TestReadDateAndTimeFunction(), TestReadDateFunction(), and TestReadWeatherRecordFunction().
GetMonth()
int Date::GetMonth () const
Get the month.
Returns
int Month
Definition at line 43 of file DATE.CPP.
{
     return month;
 }
References month.
Referenced by operator<(), operator==(), operator>(), outputFunction(), readData(), Test1(), Test2(), Test3(), Test4(), TestReadDateAndTimeFunction(), TestReadDateFunction(), and TestReadWeatherRecordFunction().
GetYear()
int Date::GetYear () const
Get the year.
Returns
int Year
Definition at line 57 of file DATE.CPP.
{
     return year;
 }
References year.
Referenced by operator<(), operator==(), operator>(), outputFunction(), readData(), Test1(), Test2(), Test3(), Test4(), TestReadDateAndTimeFunction(), TestReadDateFunction(), and TestReadWeatherRecordFunction().
SetDate()
void Date::SetDate (int d)
Set the day.
Parameters
d - Day
Returns
void
Definition at line 36 of file DATE.CPP.
{
     date = d;
 }
References date.
Referenced by readDate(), and Test3().
SetMonth()
void Date::SetMonth (int m)
Set the month.
Parameters
m - Month
Returns
void
Definition at line 50 of file DATE.CPP.
{
     month = m;
 }
References month.
Referenced by readDate(), and Test3().
SetYear()
void Date::SetYear (int y)
Set the year.
Parameters
y - Year
Returns
void
Definition at line 64 of file DATE.CPP.
{
     year = y;
 }
References year.
Referenced by readDate(), and Test3().
Member Data Documentation
date
int Date::date private
Definition at line 79 of file DATE.H.
Referenced by GetDate(), and SetDate().
month
int Date::month private
Date.
Definition at line 80 of file DATE.H.
Referenced by GetMonth(), and SetMonth().
year
int Date::year private
Month.
Definition at line 81 of file DATE.H.
Referenced by GetYear(), and SetYear().
The documentation for this class was generated from the following files:
Data Structures/DATE.H
Data Structures/DATE.CPP