Assignment 2: Test Programs/TestAVL/testAVL.cpp File Reference
testAVL.cpp File Reference
#include <iostream>
#include "../../Data Structures/AVL.h"
Functions
template<class T >
void outputFunction (const T &data)
template<class T >
void result (T expected, T actual, const string &testMessage)
void testInsertSearch ()
void testTraversal ()
void testCopyConstructor ()
void testAssignOperator ()
void testDestructor ()
AVL< int > testReturnByValue ()
void testPassByReference (AVL< int > &tree)
void testPassByConstReference (const AVL< int > &tree)
void testPassByValue (AVL< int > tree)
int main ()
Function Documentation
main()
int main ()
Definition at line 136 of file testAVL.cpp.
            {
     testInsertSearch();
     testTraversal();
     testCopyConstructor();
     testAssignOperator();
     testDestructor();
     AVL<int> tree = testReturnByValue();
     testPassByReference(tree);
     testPassByConstReference(tree);
     testPassByValue(tree);
     cout << "All tests completed." << endl;
     return 0;
 }
References testAssignOperator(), testCopyConstructor(), testDestructor(), testInsertSearch(), testPassByConstReference(), testPassByReference(), testPassByValue(), testReturnByValue(), and testTraversal().
outputFunction()
template<class T > void outputFunction (const T & data)
Definition at line 7 of file testAVL.cpp.
{
     cout << data << endl;
 }
Referenced by testAssignOperator(), testCopyConstructor(), testDestructor(), testPassByReference(), testPassByValue(), and testTraversal().
result()
template<class T > void result (T expected, T actual, const string & testMessage)
Definition at line 12 of file testAVL.cpp.
{
     cout << testMessage << ": ";
     if (expected == actual) {
         cout << "PASSED" << endl;
     } else {
         cout << "FAILED" << "\n    Expected: " << expected << " but got: " << actual << endl;
     }
 }
Referenced by printResult(), testInsertSearch(), testPassByConstReference(), TestReadDateAndTimeFunction(), TestReadDateFunction(), TestReadTimeFunction(), and TestReadWeatherRecordFunction().
testAssignOperator()
void testAssignOperator ()
Definition at line 69 of file testAVL.cpp.
{
     cout << "Test 4: Testing Assign Operator" << endl;
     AVL<int> tree;
     tree.insert(50);
     tree.insert(30);
     tree.insert(70);
     AVL<int> other;
     other = tree;
     other.insert(20);
     cout << "In-order Traversal (Should be 20, 30, 50, 70): \n";
     other.inOrder(outputFunction);
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), and outputFunction().
Referenced by main().
testCopyConstructor()
int testCopyConstructor ()
Definition at line 54 of file testAVL.cpp.
{
     cout << "Test 3: Testing Copy Constructor" << endl;
     AVL<int> tree;
     tree.insert(50);
     tree.insert(30);
     tree.insert(70);
     AVL<int> other(tree);
     other.insert(20);
     cout << "In-order Traversal (Should be 20, 30, 50, 70): \n";
     other.inOrder(outputFunction);
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), and outputFunction().
Referenced by main().
testDestructor()
int testDestructor ()
Definition at line 85 of file testAVL.cpp.
                       {
     cout << "Test 5: Testing Destructor" << endl;
     AVL<int> tree;
     tree.insert(50);
     tree.insert(30);
     tree.insert(70);
     tree.~AVL();
     cout << "<<In-order Traversal should not print anything>>\n";
     cout << "Tree: ";
     tree.inOrder(outputFunction);
     cout << endl;
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), outputFunction(), and AVL< T >::~AVL().
Referenced by main().
testInsertSearch()
void testInsertSearch ()
Definition at line 21 of file testAVL.cpp.
{
     cout << "Test 1: Testing Insert and Search Functions" << endl;
     AVL<int> tree;
     tree.insert(10);
     tree.insert(20);
     tree.insert(5);
     result(true, tree.search(10), "1.1 Search for existing value 10");
     result(true, tree.search(20), "1.2 Search for existing value 20");
     result(false, tree.search(1), "1.3 Search for non-existing value 1");
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::insert(), result(), and AVL< T >::search().
Referenced by main().
testPassByConstReference()
void testPassByConstReference (const AVL< int > & tree)
Definition at line 121 of file testAVL.cpp.
{
     cout << "Test 8: Testing Pass By Const Reference" << endl;
     result(true, tree.search(70), "8. Testing Pass By Const Reference");
     cout << "-----------------------------------------" << endl;
 }
References result(), and AVL< T >::search().
Referenced by main().
testPassByReference()
void testPassByReference (AVL< int > & tree)
Definition at line 112 of file testAVL.cpp.
{
     cout << "Test 7: Testing Pass By Reference" << endl;
     tree.insert(20);
     cout << "In-order Traversal (Should be 20, 30, 50, 70): \n";
     tree.inOrder(outputFunction);
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), and outputFunction().
Referenced by main().
testPassByValue()
void testPassByValue (AVL< int > tree)
Definition at line 127 of file testAVL.cpp.
{
     cout << "Test 9: Testing Pass By Value" << endl;
     tree.insert(100);
     cout << "In-order Traversal (Should be 20, 30, 50, 70, 100): \n";
     tree.inOrder(outputFunction);
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), and outputFunction().
Referenced by main().
testReturnByValue()
AVL<int> testReturnByValue ()
Definition at line 100 of file testAVL.cpp.
{
     cout << "Test 6: Testing Return By Value" << endl;
     AVL<int> tree;
     tree.insert(50);
     tree.insert(30);
     tree.insert(70);
     cout << "The tree will be tested on Test 7" << endl;
     cout << "-----------------------------------------" << endl;
     return tree;
 }
References AVL< T >::insert().
Referenced by main().
testTraversal()
void testTraversal ()
Definition at line 34 of file testAVL.cpp.
                      {
     cout << "Test 2: Testing Traversals" << endl;
     AVL<int> tree;
     tree.insert(50);
     tree.insert(30);
     tree.insert(70);
     tree.insert(20);
     tree.insert(40);
     tree.insert(60);
     tree.insert(80);
     cout << "In-order Traversal (Should be 20, 30, 40, 50, 60, 70, 80): \n";
     tree.inOrder(outputFunction);
     cout << "Pre-order Traversal (Should be 50, 30, 20, 40, 70, 60, 80): \n";
     tree.preOrder(outputFunction);
     cout << "Post-order Traversal (Should be 20, 40, 30, 60, 80, 70, 50): \n";
     tree.postOrder(outputFunction);
     cout << "-----------------------------------------" << endl;
 }
References AVL< T >::inOrder(), AVL< T >::insert(), outputFunction(), AVL< T >::postOrder(), and AVL< T >::preOrder().
Referenced by main().