Assignment 1: Test Programs/TestVector.cpp File Reference
TestVector.cpp File Reference
#include "../vector.h"
#include "../date.h"
#include "../time.h"
#include <iostream>
#include <string>
Functions
void printResult (string testName, bool result)
int testDefaultConstructor ()
int testParameterizedConstructor ()
int testDestructor ()
int testAddFunction ()
int testGetOperator ()
int testSetOperator ()
int testClearFunction ()
int testGrowFunction ()
int main ()
Function Documentation
main()
int main ()
Definition at line 30 of file TestVector.cpp.
            {
     //--------------------------------------
      //Test Vector's default constructor
     printResult("testDefaultConstructor", testDefaultConstructor());
     //--------------------------------------
     //Test Vector's parameterized constructor
     printResult("testParameterizedConstructor", testParameterizedConstructor());
     //--------------------------------------
     //Test Vector's Destructor
     printResult("testDestructor", testDestructor());
     //--------------------------------------
     //Test Vector's add function
     printResult("testAddFunction", testAddFunction());
     //--------------------------------------
     //Test Vector's get operator
     printResult("testGetOperator", testGetOperator());
     //--------------------------------------
     //Test Vector's Set operator
     printResult("testSetOperator", testSetOperator());
     //--------------------------------------
     //Test Vector's Clear function
     printResult("testClearFunction", testGrowFunction());
     //--------------------------------------
     //Test Vector's grow function
     printResult("testGrowFunction", testGrowFunction());
     //--------------------------------------
     cout << "All tests passed" << endl;
     return(0);
 }
References printResult(), testAddFunction(), testDefaultConstructor(), testDestructor(), testGetOperator(), testGrowFunction(), testParameterizedConstructor(), and testSetOperator().
printResult()
void printResult (string testName, bool result)
Definition at line 74 of file TestVector.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << "\"" << testName << "\"" << " " << stringResult << ".\n" << endl;
 }
Referenced by main().
testAddFunction()
int testAddFunction ()
Definition at line 111 of file TestVector.cpp.
                      {
     Vector<int> v;
     v.add(19);
     return (v.Size() == 1 ? 1 : 0);
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by main().
testClearFunction()
int testClearFunction ()
Definition at line 141 of file TestVector.cpp.
{
     Vector<int> v;
     v.add(19);
     v.Clear();
     return (v.Size() == 0 ? 1 : 0);
 }
References Vector< T >::add(), Vector< T >::Clear(), and Vector< T >::Size().
testDefaultConstructor()
int testDefaultConstructor ()
Definition at line 83 of file TestVector.cpp.
{
     Vector<int> v;
     return v.Size() == 0 ? 1 : 0;
 }
References Vector< T >::Size().
Referenced by main().
testDestructor()
int testDestructor ()
Definition at line 100 of file TestVector.cpp.
                     {
     Vector<int> v;
     v.add(19);
     v.~Vector();
     return (v.Size() == 0 ? 1 : 0);
 }
References Vector< T >::add(), Vector< T >::Size(), and Vector< T >::~Vector().
Referenced by main().
testGetOperator()
int testGetOperator ()
Definition at line 121 of file TestVector.cpp.
                      {
     Vector<int> v;
     v.add(19);
     return (v[v.Size()-1] == 19 ? 1 : 0);
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by main().
testGrowFunction()
int testGrowFunction ()
Definition at line 152 of file TestVector.cpp.
                       {
     Vector<int> v;
     v.add(100);
     v.add(101);
     return (v.Size() > 1 ? 1 : 0);
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by main().
testParameterizedConstructor()
int testParameterizedConstructor ()
Definition at line 91 of file TestVector.cpp.
{
     Vector<int> v1(-1);
     Vector<int> v2(8);
     return v1.Size() == 0 && v2.Size() == 0? 1 : 0;
 }
References Vector< T >::Size().
Referenced by main().
testSetOperator()
int testSetOperator ()
Definition at line 130 of file TestVector.cpp.
                      {
     Vector<int> v;
     v.add(19);
     v[v.Size()-1] = 20;
     return (v[v.Size()-1] == 20 ? 1 : 0);
 }
References Vector< T >::add(), and Vector< T >::Size().
Referenced by main().