Assignment 1: Test Programs/TestWeatherRecord.cpp File Reference
TestWeatherRecord.cpp File Reference
#include "WeatherRecord.h"
#include <iostream>
#include <cmath>
Functions
template<class T1 , class T2 >
bool compare (T1 num1, T2 num2)
void printResult (string testName, bool result)
void Test1 ()
void Test2 ()
void Test3 ()
int main ()
Function Documentation
compare()
template<class T1 , class T2 > bool compare (T1 num1, T2 num2)
Definition at line 45 of file TestWeatherRecord.cpp.
{
     float threshold = 0.05;
     if(fabs(num1-num2) < threshold){
         return true;
     }
     return false;
 }
Referenced by Test1(), Test2(), and Test3().
main()
int main ()
Definition at line 30 of file TestWeatherRecord.cpp.
           {
     Test1(); // Test default constructor
     Test2(); // Test parameterized constructor
     Test3(); // Test Getters and Setters
     cout << "All tests passed" << endl;
     return(0);
 }
References Test1(), Test2(), and Test3().
printResult()
void printResult (string testName, bool result)
Definition at line 56 of file TestWeatherRecord.cpp.
{
     string stringResult = result ? "Passed" : "Failed";
     cout << testName << " " << stringResult << "." << endl;
 }
Referenced by Test1(), Test2(), and Test3().
Test1()
void Test1 ()
Definition at line 65 of file TestWeatherRecord.cpp.
             {
     WeatherRecord wr;
     bool result = (compare(wr.getSpeed(), 0) && compare(wr.getSolarRad(), 0) && compare(wr.getAirTemp(), 0));
     printResult("Test 1", result);
 }
References compare(), and printResult().
Referenced by main().
Test2()
void Test2 ()
Definition at line 76 of file TestWeatherRecord.cpp.
             {
     Date d = Date(18, 4, 2003);
     Time t = Time(10, 15);
     WeatherRecord wr(d, t , 10.123, 2.93, 4.322);
     bool result = (compare(wr.getSpeed(), 10.123) && compare(wr.getSolarRad(), 2.93) && compare(wr.getAirTemp(), 4.322));
     printResult("Test 2", result);
 }
References compare(), and printResult().
Referenced by main().
Test3()
void Test3 ()
Definition at line 89 of file TestWeatherRecord.cpp.
             {
     Date d = Date(18, 4, 2003);
     Time t = Time(10, 15);
     WeatherRecord wr;
     wr.setDate(d);
     wr.setTime(t);
     wr.setSpeed(10.123);
     wr.setSolarRad(2.93);
     wr.setAirTemp(4.322);
     bool result = (compare(wr.getSpeed(), 10.123) && compare(wr.getSolarRad(), 2.93) && compare(wr.getAirTemp(), 4.322));
     printResult("Test 3", result);
 }
References compare(), and printResult().
Referenced by main().